"""FILE: lint/core/platform_contract.py

PURPOSE: Reads the vendored platform contract (lint/contracts/vidbyte-platform-contract.json, generated by cerredz/Vidbyte), validates it against the fixed schema_version 1 schema, and answers the questions rules C017-C020 ask of it: which hosts are Vidbyte API origins and whether they are live, which contract routes a request path can reach, and which error codes and API-key prefix the platform declares.
ROLE IN CODEBASE: The only reader of the vendored contract. C017 (platform-route-contract), C018 (canonical-api-host), C019 (platform-error-code-contract), and C020 (api-key-prefix-contract) call PlatformContractLoader.load; lint/core/url_flow.py uses VidbyteHosts to decide which traced URLs are platform calls.
ARCHITECTURE NOTE: The schema checks mirror cerredz/Vidbyte lint/core/platform_contract/document.py exactly (key order, record fields, sorting, uniqueness). Any problem raises PlatformContractUnavailable, which the lint runner reports as ERRORED, so a consumer rule can never pass against a missing, malformed, or wrong-version contract. Route matching treats a contract `{param}` as one non-empty path segment and a traced hole as any text, and a request matches a route when some concrete URL fits both.
FUNCTION INVENTORY: PlatformContractUnavailable; PlatformRoute, PlatformCapability, PlatformHost, PlatformContract records; PlatformContractLoader.load; UrlOrigin.parse; VidbyteHosts; RouteMatcher.match and closest.
COMMON MODIFICATION PATTERNS: A new schema_version is a coordinated change with the vidbyte lane: update the key tuples and validation here and re-vendor in the same pull request. A new Vidbyte domain goes in VIDBYTE_DOMAINS.
WHAT NOT TO DO: Do not fall back to an empty or default contract, read the contract over the network, or edit the vendored JSON; re-vendor it byte for byte as lint/contracts/README.md describes.
KNOWN EDGE CASES: The same path can appear in several routes with different methods (for example /api/skills/auth/session); matching returns all of them. An http:// URL to a listed https host is a different origin and is not listed.
RELATED DOCS: docs/design/lint-sdk-cross-repo-contracts.md; lint/contracts/README.md; cerredz/Vidbyte docs/design/lint-platform-contract-export.md.
TESTS: python lint/run.py --rule C017 (and C018, C019, C020); scratch fixtures for missing, malformed, and schema_version 2 contracts are recorded in the S4 pull request body.
"""

from __future__ import annotations

import difflib
import json
import re
from collections.abc import Sequence
from dataclasses import dataclass
from typing import cast

from lint.core.discovery import SourceCatalog

PLATFORM_CONTRACT_REL = "lint/contracts/vidbyte-platform-contract.json"
REFRESH_DOC_REL = "lint/contracts/README.md"
SCHEMA_VERSION = 1
SOURCE_REPOSITORY = "cerredz/Vidbyte"
SOURCE_GENERATOR = "scripts/generate-platform-contract.py"
TOP_LEVEL_KEYS = ("schema_version", "source", "routes", "x402_capabilities", "error_codes", "api_key_prefix", "public_api_hosts")
SOURCE_KEYS = ("repository", "commit", "generator")
ROUTE_KEYS = ("name", "methods", "path", "access", "scope", "price_cents")
CAPABILITY_KEYS = ("capability_id", "version", "price_cents", "path")
HOST_KEYS = ("url", "status")
HOST_STATUSES = ("live", "planned")
LIVE_STATUS = "live"
COMMIT_PATTERN = re.compile(r"[0-9a-f]{40}")
ACCESS_PATTERN = re.compile(r"[A-Z][A-Z0-9_]*")
METHOD_PATTERN = re.compile(r"[A-Z]+")
VIDBYTE_DOMAINS = ("vidbyte.pro", "vidbyte.ai")
RENDER_SUFFIX = ".onrender.com"
_ORIGIN = re.compile(r"(?P<scheme>[A-Za-z][A-Za-z0-9+.-]*)://(?P<host>[A-Za-z0-9.-]+)(?::(?P<port>[0-9]+))?")
_PARAM = re.compile(r"\{[^{}/]*\}")
_CLOSEST = 3


class PlatformContractUnavailable(RuntimeError):
    """The vendored platform contract is missing, untracked, undecodable, or violates the schema; consumer rules must stop."""

    def __init__(self, field: str, problem: str) -> None:
        # Keeps the failing field for fixtures and renders one message that names the file, the field, and the fix.
        self.field = field
        self.problem = problem
        super().__init__(f"{PLATFORM_CONTRACT_REL} cannot be used ({field}: {problem}). Rules C017-C020 check SDK code against this vendored copy of cerredz/Vidbyte contracts/vidbyte-platform-contract.json, so they stop instead of passing without it. Restore it with `git checkout -- {PLATFORM_CONTRACT_REL}`, or re-vendor it byte for byte as {REFRESH_DOC_REL} describes; never edit it by hand.")


def _require(condition: bool, field: str, problem: str) -> None:
    if not condition:
        raise PlatformContractUnavailable(field, problem)


def _is_int(value: object) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def _is_text(value: object) -> bool:
    return isinstance(value, str) and bool(value.strip())


@dataclass(frozen=True, slots=True)
class PlatformRoute:
    """One contract route: its stable name, HTTP methods, path template, access class, API-key scope, and price floor."""

    name: str
    methods: tuple[str, ...]
    path: str
    access: str
    scope: str | None
    price_cents: int | None

    def __post_init__(self) -> None:
        # Mirrors the producer's RouteEntry checks so a hand-edited copy fails at the field that is wrong.
        field = f"routes[{self.name!r}]"
        _require(_is_text(self.name), f"{field}.name", f"must be a non-empty string, got {self.name!r}")
        _require(isinstance(self.methods, tuple) and bool(self.methods), f"{field}.methods", f"must be a non-empty list, got {self.methods!r}")
        _require(all(isinstance(m, str) and METHOD_PATTERN.fullmatch(m) is not None for m in self.methods), f"{field}.methods", f"must be uppercase HTTP methods, got {self.methods!r}")
        _require(isinstance(self.path, str) and self.path.startswith("/"), f"{field}.path", f"must be an absolute path, got {self.path!r}")
        _require(isinstance(self.access, str) and ACCESS_PATTERN.fullmatch(self.access) is not None, f"{field}.access", f"must be a RouteAccess member name, got {self.access!r}")
        _require(self.scope is None or _is_text(self.scope), f"{field}.scope", f"must be null or a non-empty string, got {self.scope!r}")
        _require(self.price_cents is None or (_is_int(self.price_cents) and self.price_cents >= 0), f"{field}.price_cents", f"must be null or a non-negative integer, got {self.price_cents!r}")

    @property
    def normalized_path(self) -> str:
        # The path with every `{param}` written as `{}`, so two spellings of one template compare equal.
        return _PARAM.sub("{}", self.path)

    @property
    def has_params(self) -> bool:
        return _PARAM.search(self.path) is not None


@dataclass(frozen=True, slots=True)
class PlatformCapability:
    """One x402 catalog capability: its product ID, version, admission floor in cents, and mounted path."""

    capability_id: str
    version: str
    price_cents: int | None
    path: str

    def __post_init__(self) -> None:
        field = f"x402_capabilities[{self.capability_id!r}]"
        _require(_is_text(self.capability_id), f"{field}.capability_id", f"must be a non-empty string, got {self.capability_id!r}")
        _require(_is_text(self.version), f"{field}.version", f"must be a non-empty string, got {self.version!r}")
        _require(self.price_cents is None or (_is_int(self.price_cents) and self.price_cents >= 0), f"{field}.price_cents", f"must be null or a non-negative integer, got {self.price_cents!r}")
        _require(isinstance(self.path, str) and self.path.startswith("/api/x402/"), f"{field}.path", f"must be an /api/x402/ path, got {self.path!r}")

    @property
    def key(self) -> str:
        return f"{self.capability_id}@{self.version}"


@dataclass(frozen=True, slots=True)
class PlatformHost:
    """One public API origin and whether it serves traffic today (`live`) or is only intended (`planned`)."""

    url: str
    status: str

    def __post_init__(self) -> None:
        field = f"public_api_hosts[{self.url!r}]"
        _require(isinstance(self.url, str) and self.url.startswith("https://") and not self.url.endswith("/"), f"{field}.url", f"must be an https origin without a trailing slash, got {self.url!r}")
        parsed = UrlOrigin.parse(self.url)
        _require(parsed is not None and parsed.origin == self.url.lower(), f"{field}.url", f"must be a bare origin with no path, got {self.url!r}")
        _require(self.status in HOST_STATUSES, f"{field}.status", f"must be one of {list(HOST_STATUSES)}, got {self.status!r}")


@dataclass(frozen=True, slots=True)
class PlatformContract:
    """The validated vendored contract plus its raw text, so diagnostics can cite contract lines."""

    source_commit: str
    routes: tuple[PlatformRoute, ...]
    capabilities: tuple[PlatformCapability, ...]
    error_codes: tuple[str, ...]
    api_key_prefix: str
    hosts: tuple[PlatformHost, ...]
    text: str

    def line_of(self, fragment: str) -> int:
        # The 1-based line of the first occurrence of a fragment in the vendored text, or 1 when it is absent.
        index = self.text.find(fragment)
        return self.text.count("\n", 0, index) + 1 if index >= 0 else 1

    def route_line(self, route: PlatformRoute) -> int:
        return self.line_of(f'"name": {json.dumps(route.name)}')

    def code_line(self, code: str) -> int:
        return self.line_of(f"    {json.dumps(code)}")

    def cite(self, line: int) -> str:
        return f"{PLATFORM_CONTRACT_REL}:{line}"


class PlatformContractLoader:
    """Reads and validates the vendored contract, raising PlatformContractUnavailable on any problem."""

    @classmethod
    def load(cls, catalog: SourceCatalog) -> PlatformContract:
        # Presence and tracking first, then bytes, JSON, and every schema level in document order.
        path = catalog.root / PLATFORM_CONTRACT_REL
        _require(path.is_file(), "$", "the file does not exist")
        _require(PLATFORM_CONTRACT_REL in set(catalog.tracked_paths()), "$", "the file exists on disk but is not tracked by git, so CI would not see it")
        try:
            text = path.read_bytes().decode("utf-8")
        except UnicodeDecodeError as exc:
            raise PlatformContractUnavailable("$", f"the file is not UTF-8 ({exc.reason} at byte {exc.start})") from exc
        try:
            raw = json.loads(text)
        except json.JSONDecodeError as exc:
            raise PlatformContractUnavailable("$", f"the file is not valid JSON ({exc.msg} at line {exc.lineno})") from exc
        return cls.parse(raw, text)

    @classmethod
    def parse(cls, raw: object, text: str) -> PlatformContract:
        # Validates the decoded document; records validate their own fields.
        if not isinstance(raw, dict):
            raise PlatformContractUnavailable("$", "the contract must be a JSON object")
        _require(tuple(raw) == TOP_LEVEL_KEYS, "$", f"top-level keys must be exactly {list(TOP_LEVEL_KEYS)} in that order, got {list(raw)}")
        _require(_is_int(raw["schema_version"]) and raw["schema_version"] == SCHEMA_VERSION, "schema_version", f"must be {SCHEMA_VERSION}, got {raw['schema_version']!r}; this lint lane reads schema_version {SCHEMA_VERSION} only")
        source = cls._object(raw["source"], "source", SOURCE_KEYS)
        _require(source["repository"] == SOURCE_REPOSITORY, "source.repository", f"must be {SOURCE_REPOSITORY!r}, got {source['repository']!r}")
        _require(isinstance(source["commit"], str) and COMMIT_PATTERN.fullmatch(source["commit"]) is not None, "source.commit", f"must be a 40-character lowercase commit SHA, got {source['commit']!r}")
        _require(source["generator"] == SOURCE_GENERATOR, "source.generator", f"must be {SOURCE_GENERATOR!r}, got {source['generator']!r}")
        routes = tuple(cls._route(item, index) for index, item in enumerate(cls._list(raw["routes"], "routes")))
        capabilities = tuple(cls._capability(item, index) for index, item in enumerate(cls._list(raw["x402_capabilities"], "x402_capabilities")))
        codes = cls._list(raw["error_codes"], "error_codes")
        hosts = tuple(cls._host(item, index) for index, item in enumerate(cls._list(raw["public_api_hosts"], "public_api_hosts")))
        prefix = raw["api_key_prefix"]
        cls._sections(routes, capabilities, codes, prefix, hosts)
        return PlatformContract(source_commit=str(source["commit"]), routes=routes, capabilities=capabilities, error_codes=tuple(str(code) for code in codes), api_key_prefix=str(prefix), hosts=hosts, text=text)

    @staticmethod
    def _sections(routes: tuple[PlatformRoute, ...], capabilities: tuple[PlatformCapability, ...], codes: list[object], prefix: object, hosts: tuple[PlatformHost, ...]) -> None:
        # Section-level invariants the producer guarantees: sorted, unique, and non-empty where it matters.
        names = [route.name for route in routes]
        _require(len(names) == len(set(names)), "routes", "route names must be unique")
        _require(names == sorted(names), "routes", "entries must be sorted by name")
        keys = [capability.key for capability in capabilities]
        _require(len(keys) == len(set(keys)) and keys == sorted(keys), "x402_capabilities", "entries must be unique and sorted by capability_id@version")
        _require(all(_is_text(code) for code in codes), "error_codes", "every code must be a non-empty string")
        _require(codes == sorted(set(str(code) for code in codes)), "error_codes", "codes must be sorted and unique")
        _require(_is_text(prefix) and not any(ch.isspace() for ch in str(prefix)), "api_key_prefix", f"must be a non-empty token without whitespace, got {prefix!r}")
        urls = [host.url for host in hosts]
        _require(len(urls) == len(set(urls)), "public_api_hosts", "host URLs must be unique")

    @classmethod
    def _route(cls, item: object, index: int) -> PlatformRoute:
        fields = cls._object(item, f"routes[{index}]", ROUTE_KEYS)
        _require(isinstance(fields["methods"], list), f"routes[{index}].methods", "must be a JSON array")
        # Records re-check every type in __post_init__, so the casts only tell mypy what validation is about to prove.
        return PlatformRoute(name=cast(str, fields["name"]), methods=tuple(cast(list[str], fields["methods"])), path=cast(str, fields["path"]), access=cast(str, fields["access"]), scope=cast("str | None", fields["scope"]), price_cents=cast("int | None", fields["price_cents"]))

    @classmethod
    def _capability(cls, item: object, index: int) -> PlatformCapability:
        fields = cls._object(item, f"x402_capabilities[{index}]", CAPABILITY_KEYS)
        return PlatformCapability(capability_id=cast(str, fields["capability_id"]), version=cast(str, fields["version"]), price_cents=cast("int | None", fields["price_cents"]), path=cast(str, fields["path"]))

    @classmethod
    def _host(cls, item: object, index: int) -> PlatformHost:
        fields = cls._object(item, f"public_api_hosts[{index}]", HOST_KEYS)
        return PlatformHost(url=cast(str, fields["url"]), status=cast(str, fields["status"]))

    @staticmethod
    def _object(item: object, field: str, keys: tuple[str, ...]) -> dict[str, object]:
        if not isinstance(item, dict):
            raise PlatformContractUnavailable(field, "must be a JSON object")
        _require(tuple(item) == keys, field, f"keys must be exactly {list(keys)} in that order, got {list(item)}")
        return dict(item)

    @staticmethod
    def _list(item: object, field: str) -> list[object]:
        if not isinstance(item, list):
            raise PlatformContractUnavailable(field, "must be a JSON array")
        return item


@dataclass(frozen=True, slots=True)
class UrlOrigin:
    """The scheme, host, and port at the start of a URL, and where the path after them begins."""

    scheme: str
    host: str
    port: str
    end: int

    @classmethod
    def parse(cls, text: str) -> UrlOrigin | None:
        # Only an origin whose host is visibly terminated (path, query, fragment, or end of text) counts.
        match = _ORIGIN.match(text)
        if match is None:
            return None
        end = match.end()
        if end < len(text) and text[end] not in "/?#":
            return None
        return cls(scheme=match["scheme"].lower(), host=match["host"].lower().rstrip("."), port=match["port"] or "", end=end)

    @property
    def origin(self) -> str:
        return f"{self.scheme}://{self.host}{':' + self.port if self.port else ''}"


class VidbyteHosts:
    """Decides which origins belong to Vidbyte, which of those are API surfaces, and what status the contract gives them."""

    def __init__(self, contract: PlatformContract) -> None:
        # Indexes the contract's host list by full origin and by bare host name.
        self.contract = contract
        self._by_origin = {host.url.lower(): host for host in contract.hosts}
        self._listed_hosts = frozenset(origin.host for origin in (UrlOrigin.parse(host.url) for host in contract.hosts) if origin is not None)

    def is_vidbyte(self, origin: UrlOrigin) -> bool:
        # A contract host, a vidbyte.pro / vidbyte.ai host or subdomain, or a Render host whose name says vidbyte.
        host = origin.host
        if host in self._listed_hosts:
            return True
        if any(host == domain or host.endswith(f".{domain}") for domain in VIDBYTE_DOMAINS):
            return True
        return host.endswith(RENDER_SUFFIX) and "vidbyte" in host

    def is_api_surface(self, origin: UrlOrigin, rest: str) -> bool:
        # A Vidbyte URL names the API (not the website) when its host is listed, an api. host, a Render host, or its path is /api.
        if not self.is_vidbyte(origin):
            return False
        if origin.host in self._listed_hosts or origin.host.startswith("api.") or origin.host.endswith(RENDER_SUFFIX):
            return True
        path = re.split(r"[?#]", rest, maxsplit=1)[0]
        return path == "/api" or path.startswith("/api/")

    def entry(self, origin: UrlOrigin) -> PlatformHost | None:
        # The contract entry for exactly this origin (scheme, host, and port), if any.
        return self._by_origin.get(origin.origin)

    def live_urls(self) -> tuple[str, ...]:
        return tuple(host.url for host in self.contract.hosts if host.status == LIVE_STATUS)


class RouteMatcher:
    """Finds the contract routes a traced request path can reach; holes in the traced path may stand for any text."""

    def __init__(self, routes: Sequence[PlatformRoute]) -> None:
        # Pre-tokenizes every route template once.
        self.routes = tuple(routes)
        self._tokens = {route.name: self._route_tokens(route.path) for route in self.routes}

    def match(self, pieces: Sequence[str | None]) -> tuple[PlatformRoute, ...]:
        # A route matches when one concrete path satisfies both its template and the traced pieces (None is a hole).
        traced = self._traced_tokens(pieces)
        return tuple(route for route in self.routes if self._intersects(self._tokens[route.name], traced))

    def closest(self, display_path: str) -> tuple[PlatformRoute, ...]:
        # The contract routes whose templates read most like the traced path, for "did you mean" guidance.
        ranked = sorted(self.routes, key=lambda route: (-difflib.SequenceMatcher(None, route.normalized_path, _PARAM.sub("{}", display_path)).ratio(), route.name))
        return tuple(ranked[:_CLOSEST])

    @staticmethod
    def _route_tokens(path: str) -> tuple[str | None, ...]:
        # Literal characters, with None for each `{param}` (one or more characters other than "/").
        tokens: list[str | None] = []
        position = 0
        for param in _PARAM.finditer(path):
            tokens.extend(path[position:param.start()])
            tokens.append(None)
            position = param.end()
        tokens.extend(path[position:])
        return tuple(tokens)

    @staticmethod
    def _traced_tokens(pieces: Sequence[str | None]) -> tuple[str | None, ...]:
        # Literal characters, with None for each run of holes (any text, including "/" and the empty string).
        tokens: list[str | None] = []
        for piece in pieces:
            if piece is None:
                if not tokens or tokens[-1] is not None:
                    tokens.append(None)
            else:
                tokens.extend(piece)
        return tuple(tokens)

    @staticmethod
    def _intersects(route: tuple[str | None, ...], traced: tuple[str | None, ...]) -> bool:
        # Breadth-first search over (route position, inside a param, traced position) for a common accepted string.
        start = (0, False, 0)
        seen = {start}
        frontier = [start]
        while frontier:
            state = frontier.pop()
            for successor in RouteMatcher._moves(route, traced, state):
                if successor not in seen:
                    seen.add(successor)
                    frontier.append(successor)
        return (len(route), False, len(traced)) in seen

    @staticmethod
    def _moves(route: tuple[str | None, ...], traced: tuple[str | None, ...], state: tuple[int, bool, int]) -> list[tuple[int, bool, int]]:
        # Epsilon moves (a hole matching nothing, a param ending) and one-character moves both sides accept.
        i, in_param, j = state
        moves: list[tuple[int, bool, int]] = []
        if j < len(traced) and traced[j] is None:
            moves.append((i, in_param, j + 1))
        if in_param:
            moves.append((i + 1, False, j))
        route_options: list[tuple[str | None, tuple[int, bool]]] = []
        if in_param:
            route_options.append((None, (i, True)))
        elif i < len(route):
            token = route[i]
            route_options.append((None, (i, True)) if token is None else (token, (i + 1, False)))
        traced_options: list[tuple[str | None, int]] = []
        if j < len(traced):
            token = traced[j]
            traced_options.append((None, j) if token is None else (token, j + 1))
        for route_char, (next_i, next_param) in route_options:
            for traced_char, next_j in traced_options:
                if route_char is not None and traced_char is not None and route_char != traced_char:
                    continue
                if route_char is None and traced_char == "/":
                    continue
                moves.append((next_i, next_param, next_j))
        return moves
