"""Context Protocol Header

Description:
    Exports SDK dataclass contracts from the central Vidbyte lib namespace.
Purpose:
    Keeps reusable immutable data contracts in one package while feature
    packages provide compatibility import shims.
Architecture:
    - Tool contracts from tools.
    - Context, MCP, security, sandbox, and multi-agent contracts.
Relations:
    Related to vidbyte.tools, vidbyte.agents.
"""

from __future__ import annotations

from vidbyte.lib.dataclasses.agents import (
    AgentCard,
    AgentIterationSnapshot,
    AgentMessage,
    AgentRunnerConfig,
    AgentRuntimeConfig,
    AgentRuntimeStats,
    AgentSpec,
    AgentStopReason,
)
from vidbyte.lib.dataclasses.context import (
    BaseAgentContext,
    BaseContext,
    ContextArtifact,
    ContextBudget,
    ContextMessage,
    ContextPermissions,
    ContextResponse,
    ContextState,
    ContextToolCall,
    ProgressLog,
)
from vidbyte.context.primitives import (
    ArtifactContextItem,
    ContextItem,
    DocumentContextItem,
    EnvironmentContextItem,
    FileContextItem,
    GitDiffContextItem,
    MemoryContextItem,
    ProgressContextItem,
    ResponseContextItem,
    TaskContextItem,
    TextContextItem,
    ToolCallContextItem,
    TrajectoryCheckpointContextItem,
)
from vidbyte.lib.dataclasses.filesystem import FileStat, FileSystemToolConfig
from vidbyte.lib.dataclasses.mcp import McpToolDefinition
from vidbyte.lib.dataclasses.middleware import (
    MiddlewareAction,
    MiddlewareContext,
    MiddlewareDecision,
    MiddlewareEvent,
    MiddlewareHook,
    MiddlewareTransform,
)
from vidbyte.lib.dataclasses.multi_agent import (
    AgentDispatch,
    AgentReport,
    BeforeDispatch,
    CandidateFailure,
    CandidateResult,
    CompletionCheck,
    DagNode,
    EventHandler,
    EvaluationDecision,
    FinalizationContext,
    FinalizationRenderer,
    LedgerFactory,
    LedgerEvent,
    ManagerAgentCloser,
    ManagerAgentFactory,
    MultiAgentEventCallback,
    MultiAgentResult,
    MultiAgentRunState,
    MultiAgentSettings,
    NodeState,
    OrchestrationContext,
    OrchestrationRenderer,
    OrchestratorDecision,
    OrchestratorPlan,
    ReportParser,
    ReportValidator,
    RequestBuilder,
    TaskBlocker,
    TaskEvidence,
    TaskLedgerSnapshot,
    TaskRecord,
    TaskSpec,
    Verification,
    WorkerCloser,
    WorkerForkFactory,
)
from vidbyte.lib.dataclasses.sandbox import SandboxRequest, SandboxResult, SandboxTransport
from vidbyte.lib.dataclasses.security import PermissionDecision, PermissionPolicy
from vidbyte.lib.dataclasses.sessions import (
    SESSION_SCHEMA_VERSION,
    AgentUsage,
    Checkpoint,
    CheckpointPolicy,
    RunState,
    SessionMeta,
    SessionStatus,
    TraceCapture,
    UsageRollup,
)
from vidbyte.lib.dataclasses.sources import (
    ArtifactRef,
    FetchResponse,
    LlmsTxtDocument,
    LlmsTxtLink,
    LlmsTxtSection,
    MarkdownDocument,
    Selection,
    SourceResult,
    SourceSnapshot,
)
from vidbyte.lib.dataclasses.runner import RunnerHandle
from vidbyte.lib.dataclasses.prosecutor_defender_judge import (
    AllegationRecord,
    AllegationSeverity,
    DebateStageRecord,
    DefenderReportPayload,
    DefensePosition,
    DefenseRecord,
    DefenseResponsePayload,
    EvidenceCitationPayload,
    EvidenceCitationRecord,
    EvidenceSource,
    JudgeDecision,
    JudgeDecisionPayload,
    JudgeDecisionRecord,
    JudgeReasonCode,
    JudgeReportPayload,
    ProsecutorAllegationPayload,
    ProsecutorDefenderJudgeReport,
    ProsecutorReportPayload,
)
from vidbyte.lib.dataclasses.strategies import AgentResult
from vidbyte.lib.dataclasses.trace import (
    TraceField,
    TraceFieldType,
    TraceMode,
    TraceOption,
    TraceSchema,
)
from vidbyte.lib.dataclasses.tools import (
    ToolCall,
    ToolCallContext,
    ToolCallState,
    ToolParameter,
    ToolPermission,
    ToolResult,
    ToolSpec,
    ToolStatus,
)

__all__ = [
    "AgentCard",
    "AgentDispatch",
    "AgentIterationSnapshot",
    "AgentMessage",
    "AgentReport",
    "AgentResult",
    "AgentRunnerConfig",
    "AgentRuntimeConfig",
    "AgentRuntimeStats",
    "AgentSpec",
    "AgentStopReason",
    "AgentUsage",
    "AllegationRecord",
    "AllegationSeverity",
    "ArtifactRef",
    "ArtifactContextItem",
    "BaseAgentContext",
    "BaseContext",
    "BeforeDispatch",
    "CandidateFailure",
    "CandidateResult",
    "CompletionCheck",
    "ContextArtifact",
    "ContextBudget",
    "ContextItem",
    "ContextMessage",
    "ContextPermissions",
    "ContextResponse",
    "ContextState",
    "ContextToolCall",
    "DagNode",
    "DebateStageRecord",
    "DefenderReportPayload",
    "DefensePosition",
    "DefenseRecord",
    "DefenseResponsePayload",
    "DocumentContextItem",
    "EnvironmentContextItem",
    "EventHandler",
    "EvaluationDecision",
    "EvidenceCitationPayload",
    "EvidenceCitationRecord",
    "EvidenceSource",
    "FinalizationContext",
    "FinalizationRenderer",
    "FileContextItem",
    "FileStat",
    "FetchResponse",
    "FileSystemToolConfig",
    "GitDiffContextItem",
    "MemoryContextItem",
    "McpToolDefinition",
    "LlmsTxtDocument",
    "LlmsTxtLink",
    "LlmsTxtSection",
    "LedgerFactory",
    "LedgerEvent",
    "JudgeDecision",
    "JudgeDecisionPayload",
    "JudgeDecisionRecord",
    "JudgeReasonCode",
    "JudgeReportPayload",
    "ManagerAgentCloser",
    "ManagerAgentFactory",
    "MarkdownDocument",
    "MiddlewareAction",
    "MiddlewareContext",
    "MiddlewareDecision",
    "MiddlewareEvent",
    "MiddlewareHook",
    "MiddlewareTransform",
    "MultiAgentResult",
    "MultiAgentRunState",
    "MultiAgentSettings",
    "MultiAgentEventCallback",
    "NodeState",
    "OrchestrationContext",
    "OrchestrationRenderer",
    "OrchestratorDecision",
    "OrchestratorPlan",
    "PermissionDecision",
    "PermissionPolicy",
    "ProgressContextItem",
    "ProgressLog",
    "ProsecutorAllegationPayload",
    "ProsecutorDefenderJudgeReport",
    "ProsecutorReportPayload",
    "ResponseContextItem",
    "ReportParser",
    "ReportValidator",
    "RequestBuilder",
    "RunnerHandle",
    "SESSION_SCHEMA_VERSION",
    "SandboxRequest",
    "SandboxResult",
    "SandboxTransport",
    "Selection",
    "Checkpoint",
    "CheckpointPolicy",
    "RunState",
    "SessionMeta",
    "SessionStatus",
    "SourceResult",
    "SourceSnapshot",
    "TaskContextItem",
    "TaskBlocker",
    "TaskEvidence",
    "TaskLedgerSnapshot",
    "TaskRecord",
    "TaskSpec",
    "TextContextItem",
    "ToolCall",
    "ToolCallContext",
    "ToolCallState",
    "ToolCallContextItem",
    "TrajectoryCheckpointContextItem",
    "ToolParameter",
    "ToolPermission",
    "ToolResult",
    "ToolSpec",
    "ToolStatus",
    "TraceField",
    "TraceFieldType",
    "TraceMode",
    "TraceOption",
    "TraceCapture",
    "TraceSchema",
    "UsageRollup",
    "Verification",
    "WorkerCloser",
    "WorkerForkFactory",
]
