"""FILE: vidbyte/lib/jev/done/state.py

PURPOSE: Defines DONE_STATE, the one description of the batched Jev state that every done question's brief uses as its `state` section.
ROLE IN CODEBASE: Every JevDoneQuestion in this folder (multi_part.py, expert_depth.py) sets `JevBrief.state` to DONE_STATE, because JevRunState.combine() sends every enabled check's questions to Jev in one request over one shared state.
ARCHITECTURE NOTE: The shared state holds the user's request, central fields used by FAITHFUL_SCOPE, and optional per-check fields; this text names each field and its presence condition for every combination of enabled checks (skills/jev-continuation/SKILL.md step 11). It lives here so no question module imports another.
COMMON MODIFICATION PATTERNS: When a done check adds a top-level state field, describe it here with its presence condition, and name its entry fields exactly as the JEV_DONE_*_FIELD constants in vidbyte/lib/constants/jev.py spell them.
KNOWN EDGE CASES: Two checks' entries both carry `deliverable` and `evidence`; the text defines them once for both fields, and the question's focus rule keeps each question on its own field and id.
RELATED DOCS: docs/design/jev-expert-depth-done-criteria.md, docs/design/jev-multipart-done-criteria.md, and skills/asking-jev-questions/SKILL.md.
TESTS: tests/test_jev_done.py.
"""

from __future__ import annotations

# Every done question reads the same shared state, so every brief describes it with the same words.
DONE_STATE = """The state always has `request`, the user's original message with any text, code, or data they included, plus request-derived sections for enabled checks that have items. PHASE_PROGRESS has no state section and sends no question when the request has no substantive outcome stage. INPUT_SET_COVERAGE has no section and sends no question when the request yields no explicitly bounded input targets. Request-derived definitions are written before work; evidence is compiled from the current run at each finish attempt.
`deliverables` is present only for MULTI_PART and maps each requested output id to `deliverable`, `completion_signal`, and `evidence`; the first two are written from the request before work, and evidence is compiled after a finish attempt from the final answer, responses, tool calls and results, and command or test outputs.
`expert_details` is present only for EXPERT_DEPTH and maps each request-derived detail id to an entry with deliverable, detail, shallow_version, done_when, and evidence. The request-derived deliverable and detail definitions, shallow version, and done-when condition are fixed before work; evidence is compiled from the current run after a finish attempt. Each detail has its own question in the same decision batch and is judged independently; the evidence must show the named point handled beyond its shallow version and satisfy every done-when condition.
`claims` is present only for CLAIMS and maps each `parent_id.assertion_id` to its claim context and run evidence. Each claim context has five named sections: `identity` (title, description, and stated intent), `scope` (scope and qualifications), `kind`, `output`, and one `assertion` (id, statement, and completion criteria).
`target_outcomes` is present only for TARGET_OUTCOME and maps each id to `target_outcome`, `target`, `scope`, `completion_criterion`, `observed_proxy`, and `evidence`; the first four fields come from the request-derived state, while the proxy and direct evidence are compiled after work.
`motivating_cases` is present only for MOTIVATING_CASE and maps each request-named scenario id to its request-derived definition and current-run evidence. The definition records the ordinary flow, any stated testing restriction, target, unusual condition, nearby easier case, expected behavior when stated, literal inputs, and allowed exercise mode; evidence is compiled after each finish attempt.
`problems_resolved` is present only for PROBLEMS_RESOLVED and maps each observed problem, plus exactly one `original_request_completion` item, to its identity, scope, kind, repair, assertion, and evidence. It includes problems even when a later repair was attempted, so the repair and its verification remain part of the judgment.
`scope_coverage` is present only for SCOPE_COVERAGE and records request-derived dimensions plus member-level evidence from the current run. Each dimension keeps the request quote, requested change, member noun, membership rule, breadth, universe, named and excluded members, and any quoted permission for partial coverage. A request-only breadth review may widen a narrow label once when the user's wording clearly asks for broader coverage. The handoff reports work for requested members and members found in the workspace; missing required member work or missing workspace inventory remains an explicit continuation gap.
`phase_progress` is present only for PHASE_PROGRESS when the request names at least one substantive outcome stage; it maps each stage id to `stage`, `required_result`, `request_scope`, `output_criterion`, and run `evidence`. The request-derived fields are fixed before work, while evidence is compiled at each finish attempt. Preparation for a later requested result is not itself a stage unless the user asks for that preparation as an outcome. Each stage is judged separately for substantive activity or an observed blocker.
`input_set_coverage` is present only for INPUT_SET_COVERAGE when the request names explicitly bounded inputs or a user-bounded group; it maps each target id to request-derived `identity`, `scope`, `action`, and `engagement_signal`, plus run `evidence`. The request-derived fields are fixed before work, while evidence is compiled at each finish attempt and must show the requested engagement at the stated scope and depth; an empty target list creates no section and no question.
`input_exhaustion` is present only when INPUT_EXHAUSTION is enabled and maps each dynamic collection id to request-derived `collection`, `scope`, `unit`, any user-stated `expected_total`, and its `exhaustion_condition`, together with trace-backed handoff `evidence`. Evidence may include `unit_type`, distinct `visited_unit_ids`, `source_reported_total`, `last_position`, `outstanding_continuation`, `terminal_evidence`, and unresolved `failed_retrievals`; code adds deterministic count comparison when units and totals are comparable. The handoff's `missing` and `next_step` fields are continuation guidance and are never included in Jev state.
`negative_coverage` is present only when NEGATIVE_COVERAGE is enabled. Each requested inspection id maps request-derived `target` and `inspection_signal` to handoff `inspection`, `negative_conclusion`, and `incomplete_report`; the handoff `missing` note is continuation-only. Empty conclusion and incomplete-report strings mean the final answer made no such statement, zero findings alone do not show inspection, and every id is judged independently.
`guaranteed_next_actions` is handoff-only and present only when GUARANTEED_NEXT_ACTIONS is enabled and eligible candidates exist. Each candidate id maps to `outcome`, observed `trigger`, proposed `action`, and direct `evidence`; the handoff's private `necessity_basis` is excluded from Jev state. Jev judges separately whether the request and observed trigger require the action and whether run evidence shows it remains unfinished. The agent continues only when both answers for the same candidate meet the check threshold; an empty candidate set creates no section or questions.
`output_counts` is present only for OUTPUT_COUNT when the request contains one or more explicit numeric output obligations. It maps each obligation id to request-derived `obligation` fields (`description`, `target_count`, `distinct`, `unit`, `scope`, `distinctness`, and `completion_criteria`), candidate `entries` with visible values, distinct keys, and direct evidence, and code-derived `observed_count` and `target_met`. The handoff includes candidates found in the run; code computes the quantity and Jev checks whether the candidates and evidence fit the obligation. When there are no numeric output obligations, no section or question is created.
`output_extents` is present only when OUTPUT_EXTENT is enabled; it maps each explicit text-size request id to an entry containing the request-derived `target`, `output_extent` (amount, unit, and comparator), `observed` deterministic count when available, and run `evidence`. `observed` is null when code cannot safely count the named target, and evidence never includes the handoff's separate `missing` judgment. This check concerns the magnitude of text in an output; counts of distinct files, examples, records, or other entries are separate output-count obligations.
`report_action_alignment` is handoff-only and is present only when REPORT_ACTION_ALIGNMENT is enabled and post-work eligible candidates exist; it maps each candidate id to `plan`, `execution`, `final_account`, `request_relevance`, and `evidence`. A candidate requires an explicit earlier commitment that the final account refers to or implies was carried out. `request_relevance` distinguishes required outcomes from optional, unnecessary, or superseded plan steps. When no candidates exist, no section or question is created.
`assumptions_reconciled` is handoff-only and is present only when ASSUMPTIONS_RECONCILED is enabled and qualifying post-work candidates exist; it maps each candidate id to `original_assumption`, `original_basis`, `later_observation`, `affected_work`, `revision`, and `evidence`. A candidate is an explicit, consequential premise used for downstream work that later concrete run evidence materially changes. Include it whether the dependent work was revised, left unchanged, or made irrelevant, because the question judges reconciliation separately. When no qualifying candidates exist, no section or question is created. The handoff's `missing` note is continuation guidance and is not sent to Jev as evidence.
`required_actions` is present only for REQUIRED_ACTIONS when the request explicitly requires one or more actions; it maps each action id to request-derived `action` and `completion_signal` plus post-run direct `evidence`. Do not add useful, customary, or implied actions. Explicit predecessors are enforced by code from successful trace-call indices, not judged by Jev. The handoff `missing` note is continuation-only; an empty action list creates no section or question.
`user_turns` is present only for CUMULATIVE_OBLIGATIONS and contains the exact ordered user messages supplied to this run, including the current request; omitted history is unknown and is never inferred. `obligations` maps each distinct direct requirement to `instruction`, `completion_signal`, `source_turn`, compatible `related_turns`, `active`, explicit-change `status_turn`, and `status_reason`, with current-run `evidence`. Later additions, clarification, topic changes, and silence do not cancel an earlier requirement; only an explicit user withdrawal or incompatible replacement deactivates its conflicting part. A fulfillment question judges each obligation. `turn_evidence` maps each supplied turn to current observation-only responses, answer passages, tool calls and results, and command or test outputs. A separate inventory question asks once per turn, reads the actual user message and every obligation entry, and checks links or whether an omitted requirement is independently shown complete in that turn evidence. Its `missing` judgment is continuation-only. Empty obligations are valid for a turn with no direct request, and the turn inventory remains auditable.
`discovered_item_inventory` and `discovered_items` are present only for DISCOVERED_ITEM_COVERAGE. The inventory has one entry for every recorded tool-call `source_id` with its complete bounded `source_output` and candidate list, even when the output contains no collection; code checks every recorded call id and marks the check unavailable before questioning if an output is missing or exceeds the per-output or total bounds. A candidate is one concrete, independently addressable member visibly present in that source output; the handoff creates candidates only when the request asks to process collection members one by one. `discovered_items` maps each candidate id to the same `item` identity, request-faithful `requested_processing`, visible `completion_criteria`, current `processing_evidence`, and continuation-only `missing` note. The inventory question runs once for every recorded source output and asks whether its list includes exactly one candidate for each in-scope visible member, including empty lists for outputs without such members. The processing question runs once for every candidate and asks whether the requested operation and result are shown for that exact item. Candidate ids last only for one finish attempt, source fidelity is distinct from INPUT_EXHAUSTION source termination and INPUT_SET_COVERAGE fixed targets, and both inventory and processing questions join the same decision batch.
`completion_evidence` is present only in the handoff for COMPLETION_EVIDENCE and maps the one fixed `task_completion` item to the final answer's `completion_status`, `requested_outcomes`, `completed_work`, `unfinished_or_blocked`, and run `evidence`. It has no request-derived run-state section. The status and outcome summaries describe context but never prove external work; the item distinguishes what the answer communicates from observations that support it.
The handoff's `missing` summaries are continuation guidance for the main agent and are not sent to Jev as evidence. The report/action handoff's `missing` note is excluded as well because it is a generative judgment. Each question judges exactly one named item using only that item's own check fields; entries for other checks are judged by their own questions. FAITHFUL_SCOPE has no check-specific state section; it reads the five central fields request, hard_part, what_not_to_do, evidence, and missing. hard_part names one concrete requirement from the user's request in the user's terms before work begins, and what_not_to_do preserves the user's stated limits. The fixed question asks whether the latest run evidence directly shows that requirement met in its intended scope. missing is a reporter's list of possible omissions, not a verdict; claims, plans, activity, or easier neighboring work cannot replace evidence of the named requirement. Selecting hard_part does not permit ignoring any other user requirement.
Every item in an available enabled check must pass; when the handoff or Jev is unavailable, that check is unavailable and does not block the answer."""

__all__ = ["DONE_STATE"]
