from __future__ import annotations

from vidbyte.lib.constants.parallel_panel import (
    MAX_ARTIFACT_CHARS,
    MAX_ARTIFACT_NAME_CHARS,
    MAX_CANDIDATE_CHARS,
    MAX_REVIEW_CHARS,
    MAX_REVIEWERS,
    MAX_TIMEOUT_SECONDS,
    MAX_TOTAL_ARTIFACT_CHARS,
    NO_ARTIFACTS_PLACEHOLDER,
    REQUIRED_REVIEW_PROMPT_FIELDS,
    REVIEW_TRUNCATION_SUFFIX,
)
from vidbyte.lib.constants.runners import (
    MODEL_PREFIX_RUNNER_TYPE_MAP,
    MODEL_PROVIDER_RUNNER_TYPE_MAP,
    MODEL_RUNNER_TYPE_MAP,
    PROVIDER_DEFAULT_RUNNER_TYPE_MAP,
    RUNNER_TYPE_AUDIO,
    RUNNER_TYPE_EMBEDDING,
    RUNNER_TYPE_IMAGE,
    RUNNER_TYPE_TEXT,
    RUNNER_TYPE_VIDEO,
)

__all__ = [
    "MAX_ARTIFACT_CHARS",
    "MAX_ARTIFACT_NAME_CHARS",
    "MAX_CANDIDATE_CHARS",
    "MAX_REVIEW_CHARS",
    "MAX_REVIEWERS",
    "MAX_TIMEOUT_SECONDS",
    "MAX_TOTAL_ARTIFACT_CHARS",
    "MODEL_PREFIX_RUNNER_TYPE_MAP",
    "MODEL_PROVIDER_RUNNER_TYPE_MAP",
    "MODEL_RUNNER_TYPE_MAP",
    "NO_ARTIFACTS_PLACEHOLDER",
    "PROVIDER_DEFAULT_RUNNER_TYPE_MAP",
    "REQUIRED_REVIEW_PROMPT_FIELDS",
    "REVIEW_TRUNCATION_SUFFIX",
    "RUNNER_TYPE_AUDIO",
    "RUNNER_TYPE_EMBEDDING",
    "RUNNER_TYPE_IMAGE",
    "RUNNER_TYPE_TEXT",
    "RUNNER_TYPE_VIDEO",
]
