from __future__ import annotations

from vidbyte.middleware.compaction.base import BaseCompaction, CompactionMode, CompactionStats, Summarizer, TokenCounter
from vidbyte.middleware.compaction.context_compaction import MessageHistoryCompactionMiddleware, SummaryCompactionMiddleware, ToolResultCompactionMiddleware, TraceReplacementCompactionMiddleware, TraceSummaryTailCompactionMiddleware
from vidbyte.middleware.compaction.engine import ContextCompactionEngine
from vidbyte.middleware.compaction.strategies import (
    ClearExceptSystemAndLogCompaction,
    ContextSnapshotBranchTrimCompaction,
    DeduplicateToolCallsCompaction,
    DeleteMessagesByIdOrRangeCompaction,
    HeadTailToolPreviewCompaction,
    KeepLastNMessagesCompaction,
    MechanicalBloatScrubberCompaction,
    NoOpCompaction,
    QueryRelevanceFilterCompaction,
    RemoveAllToolCallsCompaction,
    RemoveLastNCompaction,
    RemoveToolCallPercentageCompaction,
    ReplaceWithTraceCompaction,
    SalienceScoreEvictionCompaction,
    SelectiveContextPruningCompaction,
    StripToolResultBodiesCompaction,
    SummaryWithBackrefsCompaction,
    SummarizeByTopicBlocksCompaction,
    SummarizeOldestNCompaction,
    SummarizeRangeCompaction,
    ToolOutputSlidingWindowCompaction,
    ToolResultClearingWithExclusionsCompaction,
    TrimToTokenBudgetCompaction,
    TrimWithProviderBoundariesCompaction,
    TruncateToolResultMessagesCompaction,
)
from vidbyte.middleware.compaction.trace_render import TraceArtifactRenderer

__all__ = [
    "BaseCompaction",
    "ClearExceptSystemAndLogCompaction",
    "CompactionMode",
    "CompactionStats",
    "ContextSnapshotBranchTrimCompaction",
    "ContextCompactionEngine",
    "DeduplicateToolCallsCompaction",
    "DeleteMessagesByIdOrRangeCompaction",
    "HeadTailToolPreviewCompaction",
    "KeepLastNMessagesCompaction",
    "MechanicalBloatScrubberCompaction",
    "MessageHistoryCompactionMiddleware",
    "NoOpCompaction",
    "QueryRelevanceFilterCompaction",
    "RemoveAllToolCallsCompaction",
    "RemoveLastNCompaction",
    "RemoveToolCallPercentageCompaction",
    "ReplaceWithTraceCompaction",
    "SalienceScoreEvictionCompaction",
    "SelectiveContextPruningCompaction",
    "StripToolResultBodiesCompaction",
    "Summarizer",
    "SummaryWithBackrefsCompaction",
    "SummarizeByTopicBlocksCompaction",
    "SummarizeOldestNCompaction",
    "SummarizeRangeCompaction",
    "SummaryCompactionMiddleware",
    "TokenCounter",
    "ToolResultCompactionMiddleware",
    "ToolOutputSlidingWindowCompaction",
    "ToolResultClearingWithExclusionsCompaction",
    "TraceArtifactRenderer",
    "TraceReplacementCompactionMiddleware",
    "TraceSummaryTailCompactionMiddleware",
    "TrimToTokenBudgetCompaction",
    "TrimWithProviderBoundariesCompaction",
    "TruncateToolResultMessagesCompaction",
]
