"""Context Protocol Header

Description:
    Re-exports central Vidbyte dataclasses, enums, errors, registries, runners, tools, and tracing protocols.
Purpose:
    Provides a stable internal/public contract boundary without moving feature implementations into `vidbyte.lib`.
Architecture:
    Imports shared contracts from focused subpackages, including multi-agent values,
    callbacks, run state, renderers, and stop-state types.
Relations:
    Consumed by the root `vidbyte` namespace and feature packages throughout the SDK.
"""

from __future__ import annotations

from vidbyte.lib.dataclasses import (
    AgentCard,
    AgentDispatch,
    AgentMessage,
    AgentReport,
    AgentRunnerConfig,
    AgentSpec,
    BaseAgentContext,
    BaseContext,
    BeforeDispatch,
    CandidateFailure,
    CandidateResult,
    CompletionCheck,
    ContextArtifact,
    ContextBudget,
    ContextPermissions,
    ContextResponse,
    ContextToolCall,
    DagNode,
    EvaluationDecision,
    EventHandler,
    FinalizationContext,
    FinalizationRenderer,
    LedgerEvent,
    LedgerFactory,
    ManagerAgentCloser,
    ManagerAgentFactory,
    MultiAgentEventCallback,
    MultiAgentResult,
    MultiAgentRunState,
    MultiAgentSettings,
    NodeState,
    OrchestrationContext,
    OrchestrationRenderer,
    OrchestratorDecision,
    OrchestratorPlan,
    ReportParser,
    ReportValidator,
    RequestBuilder,
    TaskBlocker,
    TaskEvidence,
    TaskLedgerSnapshot,
    TaskRecord,
    TaskSpec,
    ToolSpec,
    Verification,
    WorkerCloser,
    WorkerForkFactory,
)
from vidbyte.lib.enums import (
    BudgetPreset,
    MultiAgentStopReason,
    OrchestratorAction,
    PermissionPreset,
    TaskStatus,
)

__all__ = [
    "AgentCard",
    "AgentDispatch",
    "AgentMessage",
    "AgentReport",
    "AgentRunnerConfig",
    "AgentSpec",
    "BaseAgentContext",
    "BaseContext",
    "BeforeDispatch",
    "BudgetPreset",
    "CandidateFailure",
    "CandidateResult",
    "CompletionCheck",
    "ContextArtifact",
    "ContextBudget",
    "ContextPermissions",
    "ContextResponse",
    "ContextToolCall",
    "DagNode",
    "EvaluationDecision",
    "EventHandler",
    "FinalizationContext",
    "FinalizationRenderer",
    "LedgerFactory",
    "LedgerEvent",
    "ManagerAgentCloser",
    "ManagerAgentFactory",
    "MultiAgentEventCallback",
    "MultiAgentResult",
    "MultiAgentRunState",
    "MultiAgentSettings",
    "MultiAgentStopReason",
    "NodeState",
    "OrchestrationContext",
    "OrchestrationRenderer",
    "OrchestratorAction",
    "OrchestratorDecision",
    "OrchestratorPlan",
    "PermissionPreset",
    "ReportParser",
    "ReportValidator",
    "RequestBuilder",
    "TaskBlocker",
    "TaskEvidence",
    "TaskLedgerSnapshot",
    "TaskRecord",
    "TaskSpec",
    "TaskStatus",
    "ToolSpec",
    "Verification",
    "WorkerCloser",
    "WorkerForkFactory",
]
