"""FILE: vidbyte/lib/jev/compute/situations.py

PURPOSE: Defines the fixed evidence questions for fresh-agent, fork-agent, and subagent compute options.
ROLE IN CODEBASE: JevComputeRegistry gathers these question objects into one request for every enabled option.
ARCHITECTURE NOTE: Each question reads the same request, brief, facts, and recent-event state and scores one observable signal.
COMMON MODIFICATION PATTERNS: Keep exactly twelve independent questions per option and use the dynamic-compute question-writing guide.
KNOWN EDGE CASES: Missing evidence may score false; question text must not ask Jev to predict whether an action should launch.
RELATED DOCS: docs/design/jev-compute-situations.md and skills/asking-jev-dynamic-compute-questions/SKILL.md.
TESTS: tests/test_jev_compute_situations.py.
"""

from __future__ import annotations

from vidbyte.lib.dataclasses.jev import JevComputeQuestion
from vidbyte.lib.enums.jev import JevComputeQuestionKey


FRESH_AGENT_QUESTIONS = (
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_ERROR_RATE_RISING,
        instructions='Late errors can reveal that an agent is losing its grip on work as the run grows. An error trend means failures become more frequent relative to earlier visible activity. A single failed call does not establish such a trend. Have errors become more frequent toward the current end of the run? Are comparable recent actions failing more often than earlier ones? Did the rise follow growing confusion or repeated unsuccessful work? Are attempted corrections still followed by further errors? Does the remaining requested work still depend on the activity that is now failing? The signal is a visible increase across time rather than a large error count alone. If the record lacks a meaningful earlier-to-later comparison, the increase is unestablished.',
        when_true="True when visible recent events show tool errors becoming more frequent toward the run's end. The later portion contains more failed calls relative to comparable earlier activity. Those failures affect work the agent is still trying to complete.",
        when_false='False when they do not show an increase or do not allow an earlier-to-later comparison. An isolated failure or a consistently high rate without an increase does not show a late rise. If earlier activity cannot be compared with later activity, the trend remains unestablished.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_SAME_FAILURE_PERSISTS,
        instructions='An agent can spend a long run circling one unresolved failure. Persistence means the same underlying problem survives more than one attempt to address it. Different errors on different steps do not show this pattern. Is the agent still encountering the same failure after several attempts? Do the later attempts reach the same unsuccessful result? Is a shared underlying cause visible behind those attempts? Have recent fixes or retries failed to change that result? Does the unresolved failure still stand in the way of the requested outcome? The evidence must link repeated attempts to one problem that remains open. A resolved failure or merely similar wording does not establish persistence.',
        when_true='True when multiple visible attempts encounter the same unresolved failure. At least two attempts confront the same underlying problem without resolving it. The later attempt still leaves that problem open.',
        when_false='False when the failure is different, resolved, or not clearly repeated in the state. Similar error wording from unrelated causes is not the same persistent failure. A successful repair between attempts breaks the claimed recurrence.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_REPEATED_ACTION_NO_INFORMATION,
        instructions='Repeated tool work can consume the run without adding information. This signal concerns effectively identical actions whose results do not move the task forward. Repetition is useful when each result reveals something new. Has the agent repeated the same tool action without gaining relevant information? Are the inputs and returned results substantially unchanged across those calls? Did an earlier result already provide the information the agent sought again? Have later attempts changed neither the method nor the evidence obtained? Does the remaining task still need progress that these repeated calls have not supplied? The pattern requires both repeated work and an absence of useful new evidence. A repeat that tests a new condition or reveals a new result does not count.',
        when_true='True when a repeated action has the same effective inputs and adds no relevant information. The repeated calls use effectively unchanged inputs and return no new task-relevant result. Later calls leave the agent with the same evidence it already had.',
        when_false='False when the action differs, adds useful information, or the state cannot establish both facts. A changed input or a newly informative result makes a repeated tool name insufficient. If the visible results cannot be compared, the absence of new information is unproven.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_DRIFT_FROM_USER_GOAL,
        instructions="Long work can lose its connection to the outcome the user requested. Drift occurs when current actions pursue a different objective without a supported path back to that outcome. A necessary supporting step may look indirect while still serving the goal. Are the agent's recent actions diverging from the original goal? Are they producing work that the requested outcome does not call for? Did the shift begin without evidence that the original goal changed? Have recent plans or corrections continued along that unrelated path? Do the remaining requested results still lack a connection to the work now underway? The signal is a visible mismatch between the user's goal and the agent's present direction. A change of method that still advances the same outcome is not drift.",
        when_true='True when visible work pursues an outcome with no supported connection to the requested goal. The present actions pursue a different outcome rather than a necessary part of the requested one. Their connection to the original goal is unsupported by the visible work.',
        when_false='False when the work remains connected to the goal or the state does not establish a mismatch. An indirect investigation can still be aligned when it serves the requested result. A change in method alone does not show that the goal was abandoned.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_USER_CONSTRAINT_OMITTED,
        instructions="A task can fail even while its main objective receives attention. An explicit user constraint sets a boundary that the work must carry forward. A missing mention alone does not prove that the boundary has been ignored. Has the agent's current work left an explicit user constraint unaddressed? Do its visible actions or plan conflict with that stated boundary? Did the omission appear after the agent narrowed its attention to part of the task? Have recent corrections still failed to restore the missing constraint? Does the remaining requested result require that constraint to be honored? The signal needs a particular stated constraint and a visible omission or conflict. When the work is compatible with the constraint and no omission is established, answer false.",
        when_true='True when the request states a constraint and the visible plan or work leaves it unaddressed. A particular stated limit or requirement is visibly missing from current actions or plans. The omission matters to work that remains or to an output already produced.',
        when_false='False when constraints are addressed or the state does not establish a specific omission. Silence about a constraint does not prove it was ignored. When visible work honors the boundary or its treatment cannot be determined, the omission is unestablished.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_CLAIM_CONTRADICTS_EVIDENCE,
        instructions='An agent may describe its progress inaccurately after many observations. A contradiction occurs when a claim about completed work conflicts with a visible tool result. Different wording does not matter when the underlying meanings agree. Does a recent agent claim contradict the tool evidence for that work? Does the claimed result differ from what the relevant call actually returned? Did the agent overlook a failure or limitation shown in that result? Have subsequent actions continued as though the unsupported claim were true? Does the remaining task depend on that claimed result being accurate? The signal requires a specific claim and a conflicting observation about the same work. A claim without comparable evidence cannot establish a contradiction.',
        when_true="True when a visible recent claim conflicts with the result of the relevant tool call. The claim and the returned result concern the same action or outcome. Their meanings conflict in a way that changes the run's account of progress.",
        when_false='False when the claim agrees with the result or the state lacks both sides of the comparison. A difference in phrasing without a difference in meaning is not a contradiction. If the relevant claim or tool result is unavailable, the comparison cannot be made.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_DISPROVEN_ASSUMPTION_CONTINUES,
        instructions='An early assumption can become a liability after the run produces contrary evidence. Continued reliance means later actions still depend on that same premise despite its disproof. Merely exploring an uncertain idea is different from ignoring a known contradiction. Is the agent still acting on an assumption the run has disproven? Do later actions require the premise that earlier evidence ruled out? Did the contradiction arise before those later actions were chosen? Have attempted revisions left the underlying premise intact? Does the remaining requested work still depend on decisions built from that premise? The signal requires visible disproof followed by consequential continued reliance. If the premise was revised or the later action uses a different basis, answer false.',
        when_true='True when later visible work still relies on a premise already contradicted by run evidence. The contradiction appears before later work that still requires the rejected premise. That later reliance affects a decision, action, or claimed result.',
        when_false='False when no disproof and continued reliance are both visible in the state. Testing an uncertain idea before it is disproven does not count. If later actions use a revised premise or no consequential reliance is visible, answer false.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_EARLIER_EVIDENCE_IGNORED,
        instructions="A long run can leave important earlier evidence outside the agent's current focus. Ignoring evidence means later work conflicts with or bypasses an earlier verified finding that still matters. Omission of an old detail is harmless when it no longer bears on the task. Is the agent overlooking earlier evidence relevant to its current step? Do recent claims or actions fail to account for that finding? Did the finding already settle or constrain the issue now being revisited? Have later attempts proceeded without using the established information? Does the remaining requested work still require that evidence to be considered? The signal needs an identifiable earlier finding and later work that should have used it. If relevance or the later omission is unclear, answer false.",
        when_true='True when later visible work overlooks earlier verified evidence relevant to its current step. The earlier finding bears directly on the current step or unresolved problem. Later actions or claims proceed as though that finding were unavailable.',
        when_false='False when the evidence is accounted for, no longer relevant, or not visible enough to compare. An older detail that no longer matters need not be repeated. Without both a relevant finding and a later omission, the pattern is unsupported.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_FIX_INTRODUCES_FAILURE,
        instructions='An attempted repair can create a new obstacle while addressing an old one. This signal concerns a new failure that follows and is attributable to a visible fix. Temporal order alone cannot show that the fix caused an unrelated problem. Has a recent fix introduced a new failure into the run? Does the new failure affect behavior changed by that fix? Was the problem absent before the attempted repair? Have subsequent attempts struggled with the new failure as well as the original issue? Does this added obstacle now impede the requested outcome? The evidence must connect a particular change with a newly observed failure. A preexisting or unrelated error does not establish the pattern.',
        when_true='True when a visible fix attempt is followed by a newly reported failure attributable to that change. The new failure appears after the attempted change and concerns behavior that change affected. The record links the attempted repair to the new problem.',
        when_false='False when no new failure follows a fix or the state cannot connect the two. A failure already present before the fix is not newly introduced. A later error outside the changed behavior does not establish this causal link.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_PLAN_OSCILLATES,
        instructions='Repeated changes of plan can signal that an agent is no longer holding a stable path through the task. Oscillation means it returns between directions without verified progress. A single revision after new evidence is ordinary adaptation. Is the agent switching back and forth between plans without advancing the work? Do later plans revisit an earlier direction without a new reason? Did the changes arise despite little new evidence about the task? Have recent attempts repeated these reversals instead of resolving a step? Does the remaining requested result still lack progress after those changes? The signal is repeated reversal together with an absence of measurable gain. Evidence-based revisions that produce progress do not count.',
        when_true='True when repeated direction changes are visible without verified progress on the requested work. Several returns between competing directions occur without a verified gain. The requested outcome remains open despite those reversals.',
        when_false='False when the plan is stable, changes for evidence-based reasons, or makes visible progress. One change of plan after new evidence is ordinary adaptation. Revisions that settle an item or produce measurable progress are not unproductive oscillation.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_LOST_CONTINUITY,
        instructions="A growing run can strain an agent's grasp of what it has already established. Lost continuity appears when later work treats settled facts, completed steps, or current status as unknown or different. Run length alone does not show confusion. Is the agent losing track of established work as the run grows? Do recent actions repeat discovery of facts already verified? Did this confusion emerge after substantial earlier activity accumulated? Have attempted reminders or corrections failed to restore a consistent view? Does the remaining task require the missing continuity to proceed correctly? The signal is visible confusion about earlier state with consequences for current work. A deliberate recheck or a large context by itself is insufficient.",
        when_true='True when later events show confusion or loss of established state as the run grows. Later work treats an earlier settled fact or completed step as unknown or different. That confusion changes what the agent does next.',
        when_false='False when only run size is visible or the events do not establish a continuity problem. A long history by itself cannot show lost continuity. A deliberate confirmation of an earlier result is not confusion when the agent still understands that result.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FRESH_AGENT_BRIEF_SUPPORTS_RESUME,
        instructions='A fresh agent needs a trustworthy handoff to continue the same task. Resume readiness means the retained notes preserve the goal, verified progress, and the next unresolved work. A compact handoff need not repeat every action in the run. Do the retained notes contain enough information for a fresh agent to resume? Do they identify both completed work and what remains open? Are the relevant facts grounded in observations rather than unsupported conclusions? Have recent updates preserved the current position after changes in the plan? Can the remaining user goal be pursued from those notes without guessing essential context? The signal is a coherent, evidence-backed starting point for continuation. Missing goal, progress, or next-step information weakens this signal.',
        when_true='True when the retained notes support the goal, verified progress, current position, and an actionable next step. The notes identify what has been verified and what remains to be done. A continuing agent can use them without inventing missing task facts.',
        when_false='False when essential context is missing, unclear, or only inferable from unsupported assumptions. A summary that omits an essential constraint or current position is not a reliable handoff. Unsupported conclusions cannot replace the observations needed to resume.',
    ),
)


FORK_AGENT_QUESTIONS = (
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_DISTINCT_APPROACHES,
        instructions='Forking has a purpose when an unresolved goal admits genuinely different routes. Distinct approaches use different central methods rather than cosmetic variations of one plan. Their plausibility must come from the work already known. Are at least two different approaches visible for the same unresolved goal? Would they investigate or change the problem in materially different ways? Did the alternatives arise from a real uncertainty in the current work? Have any of the approaches already been attempted without settling the choice? Do the remaining requested results give both approaches a reason to be considered? The signal is multiple plausible paths to one goal with meaningful differences between them. Different labels for the same work or paths to unrelated goals do not count.',
        when_true='True when the state supports at least two different, plausible approaches to one unresolved requested goal. Each route changes the central method or hypothesis while addressing the same remaining outcome. Both have enough support in the run to be plausible alternatives.',
        when_false='False when fewer than two such approaches are supported or they address different goals. Two names for one method do not create separate approaches. Paths aimed at different goals cannot be compared as alternatives for one decision.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_SAME_VERIFIED_STATE,
        instructions="Alternative paths are easier to compare when they begin from the same established position. A shared starting point includes the verified facts and completed work each path may rely on. One path cannot start from an outcome the other has yet to produce. Can the alternative paths start from the same verified state? Do they rely on the same known facts about the unresolved goal? Did earlier work establish those facts before either path would begin? Have current plans avoided making one path depend on the other's result? Would their remaining work still be comparable from that common position? The signal is a starting point supported for every proposed path. A path requiring unverified or path-specific groundwork weakens the comparison.",
        when_true='True when both paths can use the same verified progress, facts, and current position. Both routes may rely on the same completed work and observations before either begins. Neither needs a result that only the other route could produce.',
        when_false='False when either path requires a different or not-yet-established starting state. A route based on an unverified premise lacks the shared foundation. If one route needs path-specific groundwork before comparison, the starting states differ.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_INDEPENDENT_PATHS,
        instructions="A fork can examine alternatives separately only when the paths can advance on their own. Independence concerns intermediate work, even if the paths meet for a final comparison. Sharing a goal does not force their steps to be sequential. Can the alternative paths proceed without each other's intermediate results? Does each path have enough current information to take its next step? Did any dependency between their plans arise from the work already done? Have current attempts kept one path from waiting on another's partial output? Can the remaining goal receive separately produced results from both paths? The signal is independent progress followed by a possible common evaluation. If one path must consume another's result before starting, this signal is absent.",
        when_true="True when the described next actions on each path do not require the other's output. Each route can take its next meaningful steps using information already available. Their results may meet later without either route consuming the other's intermediate output.",
        when_false="False when one path depends on the other's result or the state cannot establish independence. A serial dependency makes the routes stages of one path. If the necessary next inputs are unclear, independence has not been established.",
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_BOUNDED_EXPERIMENTS,
        instructions='Exploring alternatives is more useful when each route has a finite test. A bounded experiment names an action and an observable point at which its result can be judged. An open-ended investigation offers no comparable stopping place. Can each alternative approach be tested within a clear boundary? Does each proposed test have an inspectable result? Did the uncertainty in the run identify what each test needs to learn? Have current plans specified actions rather than broad aspirations? Would the remaining goal allow the tests to stop once their evidence is available? The signal requires bounded work for every compared path. A path with no action, endpoint, or observable result is not yet a testable alternative.',
        when_true='True when each path has a bounded action and an observable result or stopping point. Every route names a finite action and an observation that ends its test. The outcomes can be inspected without letting either investigation expand indefinitely.',
        when_false='False when either path is open-ended or has no inspectable result. A broad idea without an action or endpoint is not an experiment. If even one route lacks an observable stopping point, the pair is not bounded.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_COMMON_SUCCESS_CONDITION,
        instructions="Different approaches are comparable when the same requested outcome can judge them. A common success condition describes the result that matters, independent of the method used. Separate methods may still return evidence in different forms. Can both paths be assessed against one success condition? Does that condition follow from the user's unresolved goal? Did earlier work clarify what a successful result would look like? Have the current alternatives preserved that same target while varying their methods? Would their remaining outcomes answer the same question about completion? The signal is one outcome standard applicable to both paths. Unrelated measures of success leave the paths incomparable.",
        when_true='True when one request-grounded success condition applies to both paths. The same requested outcome can be used to judge the results of both routes. Their methods may differ while the standard for success remains fixed.',
        when_false='False when their outcomes require unrelated success conditions or no common condition is stated. Unrelated output goals prevent a common comparison. If success has not been defined for both routes, no shared condition is visible.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_NO_CLEAR_WINNER,
        instructions='Forking can gather evidence when plausible paths remain unsettled. No clear winner means current observations do not already justify choosing one path over the others. Missing information alone does not prove that all approaches are equally good. Do the plausible paths still lack a clear evidence-based winner? Does each retain support after the observations made so far? Did any earlier result fail to settle the choice between them? Have current attempts left their relative merits unresolved? Does the remaining goal still require this choice to be made? The signal is an open comparison between supported alternatives. If one path is already established as superior or the alternatives themselves are unsupported, answer false.',
        when_true='True when available relevant evidence does not establish one path as the clear choice. At least two supported routes remain plausible after considering the current observations. No relevant result already settles which one better serves the goal.',
        when_false='False when the evidence clearly favors one path or is too incomplete to compare them. Clear evidence favoring one route removes the unresolved choice. Total lack of support for the alternatives is also insufficient to call them a meaningful tie.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_NON_FORECLOSING,
        instructions='Comparing approaches is easier when testing one does not destroy the chance to test another. A nonforeclosing path leaves the relevant resources, state, and permissions available for its alternatives. Reversibility can matter when a trial changes shared work. Can one path be tried while the other plausible paths remain available? Does its proposed work preserve what the alternatives need? Did earlier actions reveal irreversible effects or order constraints? Have current plans accounted for changes that could close another route? Would the remaining goal still permit comparison after one path is tested? The signal is a visible way to keep alternatives open during a trial. An irreversible first action that rules out another path defeats it.',
        when_true='True when visible actions and constraints allow the alternatives to remain open after a trial. A trial can finish without consuming or changing what another route needs. Any effects are reversible or otherwise leave the alternatives usable.',
        when_false='False when one path forecloses another or the state cannot establish that options remain open. An irreversible action that closes another route forecloses comparison. When the effects of the first trial are unknown, continued availability is not established.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_ISOLATED_SIDE_EFFECTS,
        instructions="Separate paths can interfere when they change the same resources. Isolation means the effects of one path do not silently alter the inputs or results of another. A read-only path may be isolated even when it examines shared material. Can the paths keep their writes and other side effects separate? Do their proposed actions touch distinct or controlled targets? Did earlier work expose shared mutable resources that would cause interference? Have current plans provided a way to contain overlapping effects? Would the remaining comparison still reflect each path's own result? The signal is bounded, inspectable effects for every alternative. Uncontrolled overlap makes separate outcomes unreliable.",
        when_true='True when the state supports separate targets or controlled effects for each path. The routes use disjoint mutable targets or a visible method for containing overlap. An outcome from one route remains attributable to that route.',
        when_false='False when effects overlap in an uncontrolled way or the state cannot establish isolation. Uncontrolled writes to the same target can contaminate both outcomes. Without identifiable targets or containment, isolation cannot be inferred from separate path names.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_PARALLEL_EVIDENCE,
        instructions="Independent paths can produce evidence before either needs the other's intermediate work. Parallel evidence means each route has a result that can be inspected on its own. A shared final decision may come after both results exist. Can each path yield evidence without waiting for another path's partial result? Does each have an independently observable outcome? Did the current plan expose any serial handoff between their tests? Have existing attempts produced or defined separate result channels? Would the remaining comparison be possible once both outcomes arrive? The signal is separately obtainable evidence for the same unresolved decision. A chain in which one result creates the next path's inputs is sequential, not parallel.",
        when_true='True when each path can yield an inspectable result without waiting on the other path. Each route can produce its own inspectable finding from inputs already available. The findings may be compared after both are produced.',
        when_false="False when results depend on serial handoffs or the state does not show separate outcomes. A result that requires another route's partial finding is serially dependent. A plan that names separate routes but no separate outcomes does not establish this signal.",
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_DIFFERENT_HYPOTHESES,
        instructions='Alternative commands may still test the same underlying idea. Distinct hypotheses offer different explanations or mechanisms for the unresolved goal. Their difference should change what a result would teach the run. Do the paths test different meaningful hypotheses? Would their outcomes distinguish between competing explanations? Did earlier observations leave more than one explanation plausible? Have current attempts treated those explanations separately? Would the remaining work change direction based on which hypothesis receives support? The signal is a substantive difference in what the paths investigate. Merely changing the tool or wording while testing one claim does not count.',
        when_true='True when the paths test distinct, request-relevant explanations or mechanisms. Each route tests a different explanation or mechanism relevant to the unresolved goal. Their possible results would teach the run different things.',
        when_false='False when they test the same claim or their difference has no bearing on the goal. Different commands can still test the same claim. An alternative whose hypothesis has no bearing on the goal does not add a meaningful comparison.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_SELECTABLE_RESULT,
        instructions="Exploration only informs the main task when a path's result can be used. A selectable result can be compared with another result and then chosen or integrated. An isolated artifact with no route into the work cannot guide the decision. Can a path's result be selected or incorporated into the main work? Does its output address a concrete unresolved part of the goal? Did earlier work establish how such an output would be judged? Have current plans left a place to apply the result? Would the remaining requested outcome benefit from the selected or combined evidence? The signal is a clear connection from path result to the task's next decision. A result that cannot influence the task is not selectable here.",
        when_true="True when the state supports comparing a path result and using it toward the requested outcome. The run has a supported way to compare the output with another path's output. A selected or combined result can then advance the requested work.",
        when_false='False when results cannot guide a choice or connect back to the requested work. An interesting artifact with no use in the task is not selectable. If no comparison or integration step is supported, its value to the main path is unestablished.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.FORK_AGENT_REQUEST_ALIGNED_PATHS,
        instructions="Forking should compare routes to the task the user actually gave. Alignment means each path advances or verifies the same requested outcome. Technical interest alone does not make a side path relevant. Do all proposed alternatives address the user's unresolved goal? Does each path have a supported connection to the requested result? Did the alternatives arise from uncertainty about that result rather than an unrelated concern? Have current plans kept their work within the user's scope? Would the remaining requested outcome be served by results from either path? The signal requires every compared route to matter to the same task. A path that pursues unrelated work does not supply evidence for this fork.",
        when_true="True when each path has a supported connection to the user's requested outcome. Both routes address the same user-defined result or a necessary verification of it. Their work remains inside the requested scope.",
        when_false="False when a path pursues unrelated work or its connection to the request is unsupported. Technical side work unrelated to the outcome does not become a valid route. A missing connection from either path to the user's goal makes the pair unaligned.",
    ),
)


SUBAGENT_QUESTIONS = (
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_BOUNDED_SUBTASK,
        instructions="A helper needs a piece of work with a recognizable edge. A bounded subtask has its own starting point and a point where its work is complete. A broad responsibility with no end condition remains part of the main task. Is there a bounded unit of work within the current task? Can its start and finish be described without inventing new scope? Did the user's goal or the agent's progress expose that unit? Have current plans kept it separate from open-ended decision making? Would completing that unit return a result needed by the remaining work? The signal is a discrete task whose completion can be observed. Vague extra work with no stopping condition does not establish it.",
        when_true='True when the state shows a scoped unit of work with a clear result or stopping point. The unit has a recognizable starting point and an observable way to finish. Its result can be returned without transferring responsibility for the whole task.',
        when_false='False when the work is open-ended, dependent on missing decisions, or unsupported by the state. A broad assignment with no stopping condition remains open-ended. If scope or completion depends on an unresolved central decision, the unit is not independently bounded.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_EXPLICIT_DELIVERABLE,
        instructions='Independent work needs an output the main agent can inspect. A deliverable may be a finding, artifact, or verified result with a clear completion condition. Mere activity does not tell the main agent what was accomplished. Does the separate work have an explicit deliverable? Can the expected output be named before the work begins? Did the requested outcome or current plan define why that output matters? Have current attempts identified how completion would be recognized? Would the remaining task know what to do with the returned result? The signal is a concrete and inspectable handoff product. Work described only as helping or investigating lacks that boundary.',
        when_true='True when the state identifies a concrete output or finding the helper would return. The output can be named before the helper starts and inspected when it returns. Completion means producing that output rather than merely spending effort.',
        when_false='False when the expected result is unspecified, uninspectable, or not distinct from activity. An instruction to help or investigate does not name a deliverable. When no one can tell what should be returned, the handoff condition is missing.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_PACKAGED_INPUTS,
        instructions='A helper can act independently only when it receives the information its unit of work requires. Packageable inputs include the task boundary, relevant evidence, and any stated constraints. Hidden history cannot be assumed to travel with the helper. Are the required starting inputs available for a separate subtask? Can those inputs be identified without reconstructing the entire run? Did earlier work verify the facts on which the subtask depends? Have current plans left any essential choice or source unspecified? Would the remaining goal still be reachable from the information that can be handed over? The signal is sufficient visible context for the bounded work. A missing decision or unverifiable premise makes the handoff incomplete.',
        when_true='True when the required starting context is visible in the original task, verified notes, or recent work. The required scope, constraints, and evidence can be passed with the assignment. The helper would not need hidden history to determine its next steps.',
        when_false='False when essential context depends on unavailable history, assumptions, or new decisions. A missing source or unresolved choice cannot be supplied by assumption. If the visible material is insufficient to begin, the inputs are not packageable.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_OWN_TOOL_INTERACTIONS,
        instructions="A helper is most useful when its work includes actions it can perform within its own scope. Separate tool interactions are calls or inspections that do not require the main agent to execute each step. A simple judgment already available to the main agent may offer no separate work. Does the subtask require its own bounded tool interactions? Can those interactions be performed without borrowing the main agent's active step? Did the unfinished work identify resources or checks for the helper to inspect? Have current plans separated those actions from central reasoning? Would their results contribute evidence needed for the remaining goal? The signal is distinct executable work inside a clear boundary. Actions that cannot be separated from the main path do not establish it.",
        when_true="True when the work unit requires distinct tool actions that can be performed within its scope. The helper has specific actions or checks to carry out within its bounded scope. Those actions can produce results independently of the main agent's active step.",
        when_false='False when it needs no separate interactions or its actions are inseparable from the main path. A simple restatement of information already known offers no separate tool work. If the necessary actions belong to an inseparable main-path step, this signal is absent.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_NO_MIDTASK_DECISIONS,
        instructions='Independent work slows down when every next step needs direction from the main agent. A self-directed subtask has enough scope, inputs, and stopping rules to proceed between handoff and return. New user-facing choices can break that independence. Can the helper complete the unit without a decision from the main agent midway? Are the next steps determined by the bounded task and its inputs? Did earlier work settle the choices that would otherwise interrupt it? Have current plans avoided an unresolved approval or task-defining branch? Would the remaining work receive a completed result rather than a request for repeated direction? The signal is an uninterrupted path from assignment to deliverable. If a central decision is still required during execution, answer false.',
        when_true='True when its scope, inputs, and stopping condition let the helper finish without an intervening choice. The assignment supplies a stopping condition and enough direction for the helper to proceed. No task-defining choice must be returned to the main agent before completion.',
        when_false='False when the path depends on a new decision or the shared state does not settle that question. An unresolved approval or new user-facing choice interrupts the work. If a midtask decision remains hidden or unspecified, independence is unestablished.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_SEPARATE_FROM_CENTRAL_PATH,
        instructions="A helper can support a run without owning its central choice. Separate work supplies evidence or an artifact while the main agent retains the task-defining decision. A delegated step that decides the whole direction is no longer peripheral. Is the proposed subtask separate from the main agent's central decision path? Does it produce support rather than choose the main outcome? Did the current run identify a central choice that must stay with the main agent? Have recent plans kept the helper's responsibility bounded around that choice? Would the remaining task still leave the final direction with the main agent? The signal is a supporting work unit with a clear handback. If the helper would make the central decision itself, this signal is absent.",
        when_true="True when it produces supporting work without owning a decision reserved for the main path. The returned work informs or supports the main agent's decision. The helper's scope ends before the central choice is made.",
        when_false="False when it performs the central choice itself or the relationship is unclear. If the helper must choose the task's direction, it owns more than supporting work. An unclear boundary between support and final decision does not establish separation.",
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_INTEGRATABLE_RESULT,
        instructions="A separate result matters only when the main work can use it. Integration means the returned finding or artifact connects to an unresolved step or requested result. A detached output with no consumer adds work without progress. Can the subtask's result be integrated into the main task? Is there a specific unfinished step that can use the output? Did earlier work establish the need for that information or artifact? Have current plans identified how the result would be checked and applied? Would the remaining user goal advance once the result is returned? The signal is a traceable route from helper output to main-task progress. A result with no supported use does not establish it.",
        when_true='True when the result can be inspected and applied to a current request or unresolved step. A particular unfinished step can receive and use the returned finding or artifact. The main agent has a visible way to inspect it before applying it.',
        when_false='False when there is no supported route to use the result in the main work. An output with no consumer cannot advance the run. If its connection to the requested result is only assumed, integration is unestablished.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_PARALLEL_PROGRESS,
        instructions="Separate work can advance while the main agent handles another part of the task. Parallel progress requires each side to have its own inputs until a later integration point. Shared final use does not make their earlier actions dependent. Can the subtask proceed while the main agent continues other work? Do both paths have enough information to advance independently now? Did the current run reveal a dependency that would force one to wait? Have recent plans kept their intermediate steps distinct? Would the remaining goal benefit from results that arrive from both paths? The signal is simultaneous possible progress before final integration. A task that must wait for the main path's next result is sequential.",
        when_true="True when the state shows independent work that does not wait on the main path's intermediate result. The helper and main agent can advance separate steps from information already available. They need not exchange intermediate results before making progress.",
        when_false="False when the subtask and main step are sequentially dependent or the dependency is unclear. A subtask that waits for the main agent's next result is sequential. Shared final integration alone does not prove parallel progress if the earlier steps remain dependent.",
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_FOCUSED_CONTEXT,
        instructions="A helper can examine a coherent slice of evidence without carrying the entire run. A focused context contains the material needed for one bounded question or item. A topic label alone does not identify that material. Is there a distinct evidence set for the proposed subtask? Can its relevant material be separated from the agent's other active work? Did earlier observations identify the sources or items that belong in that set? Have current plans kept the investigation within that boundary? Would the remaining goal use a conclusion drawn from this focused material? The signal is a recognizable evidence slice with a purpose in the task. An undefined or inseparable body of material does not establish it.",
        when_true="True when the state identifies a bounded evidence set distinct from other active run material. The subtask's relevant material has a recognizable boundary and purpose. A helper could inspect that material without carrying unrelated active work.",
        when_false='False when the material is not separable or no focused evidence set is shown. A topic name without identifiable evidence does not create a focused set. If essential material cannot be separated, the context boundary is unsupported.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_PARTITIONABLE_ITEMS,
        instructions="Some requested work contains several items that can be handled separately. Partitionable items have their own inputs and outcomes, even when the final answer collects them. A numbered list is not enough if every item depends on a shared intermediate choice. Are multiple unfinished items separable into independent work units? Can each item be handled from its own known inputs? Did the request or current progress identify the items distinctly? Have recent plans avoided making one item's result a prerequisite for another? Would the remaining task accept their separate results before combining them? The signal is at least two independent item-level units. Fewer items or hidden dependencies do not establish partitionability.",
        when_true='True when the state shows at least two unfinished items with separable inputs and outcomes. At least two unfinished items have their own inputs and inspectable outcomes. Their results can be combined after independent work finishes.',
        when_false='False when fewer than two such items are supported or their work is interdependent. A list whose items all require one shared intermediate decision is not partitionable. When item boundaries or dependencies are unknown, independence cannot be inferred.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_ISOLATED_WRITES,
        instructions="A helper's changes should not collide with the main agent's active changes. Isolation may come from read-only work or from distinct mutable targets. Shared names do not prove that the underlying resources are separate. Can the subtask avoid conflicting writes or shared mutable state? Are its intended targets separate from the main agent's current targets? Did earlier actions expose any overlap that would make coordination necessary? Have current plans bounded or isolated the effects of both paths? Would the remaining work still have an unambiguous result after those changes? The signal is a visible way to prevent competing mutations. Uncontrolled overlap or unknown write targets leave it unsupported.",
        when_true='True when visible scope permits read-only work or changes to isolated targets. The helper is read-only or works on targets distinct from current main-agent mutations. The resulting changes can be attributed without conflicting updates.',
        when_false='False when mutable targets overlap or the state does not establish safe separation. Concurrent changes to the same mutable target create an unresolved collision. Unknown write targets cannot support an isolation judgment.',
    ),
    JevComputeQuestion(
        key=JevComputeQuestionKey.SUBAGENT_SUBSTANTIVE_WORK,
        instructions='A separate helper should have meaningful work to complete within its boundary. Substantive work involves investigation, transformation, or verification that requires several coherent actions. An isolated trivial step may be executable without being a useful work unit. Is there enough substantive work for an independent helper? Does the unit require more than a single obvious action? Did the remaining task expose a meaningful question or artifact for that work? Have current plans shown several connected steps within the unit? Would completing those steps materially advance the requested outcome? The signal is a bounded but worthwhile body of work. Trivial or speculative activity does not establish it.',
        when_true='True when the bounded unit contains meaningful investigation, transformation, or verification. The unit contains a coherent sequence of investigation, transformation, or verification steps. Finishing it would provide material progress toward the requested outcome.',
        when_false="False when it is trivial, unsupported, or inseparable from the main agent's work. One trivial action does not justify a separate work unit merely because it can be assigned. Speculative work with no bounded result is also insufficient.",
    ),
)

__all__ = ["FORK_AGENT_QUESTIONS", "FRESH_AGENT_QUESTIONS", "SUBAGENT_QUESTIONS"]
