"""FILE: vidbyte/lib/jev/compute/situations.py

PURPOSE: Defines the fixed evidence questions for fresh-agent, fork-agent, and subagent compute options.
ROLE IN CODEBASE: JevComputeRegistry gathers these question objects into one request for every enabled option.
ARCHITECTURE NOTE: Each question reads the same request, brief, facts, and recent-event state and scores one observable signal.
COMMON MODIFICATION PATTERNS: Keep exactly twelve independent questions per option and use the dynamic-compute question-writing guide.
KNOWN EDGE CASES: Missing evidence may score false; question text must not ask Jev to predict whether an action should launch.
RELATED DOCS: docs/design/jev-compute-situations.md and skills/asking-jev-dynamic-compute-questions/SKILL.md.
TESTS: tests/test_jev_compute_situations.py.
"""

from __future__ import annotations

from vidbyte.lib.dataclasses.jev import JevComputeQuestion
from vidbyte.lib.enums.jev import JevComputeQuestionKey


def _question(
    key: JevComputeQuestionKey,
    lead_in: tuple[str, ...],
    question: str,
    when_true: str,
    when_false: str,
) -> JevComputeQuestion:
    """Build one fixed Jev question from its eight-sentence evidence lead-in."""
    if len(lead_in) != 8:
        raise ValueError(f"{key.value} needs exactly eight introductory sentences")
    return JevComputeQuestion(
        key=key,
        instructions=" ".join((*lead_in, question)),
        when_true=when_true,
        when_false=when_false,
    )


FRESH_AGENT_QUESTIONS = (
    _question(
        JevComputeQuestionKey.FRESH_AGENT_ERROR_RATE_RISING,
        (
            "This check looks for tool errors becoming denser near the run's current end.",
            "`request` identifies the task whose progress is being tracked.",
            "`brief` summarizes verified progress and unresolved problems.",
            "`facts` reports exact counts of errors and repeated calls.",
            "`recent` preserves the newest numbered run events in order.",
            "Compare later error events with earlier activity that remains visible.",
            "One isolated error does not establish a rising rate.",
            "If the state lacks a comparable time span, treat the rise as absent.",
        ),
        "Has the rate of tool errors risen late in the run?",
        "True when visible recent events show tool errors becoming more frequent toward the run's end.",
        "False when they do not show an increase or do not allow an earlier-to-later comparison.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_SAME_FAILURE_PERSISTS,
        (
            "This check concerns recurrence of one unresolved failure across attempts.",
            "`brief` records open failures and approaches already tried.",
            "`recent` shows the newest actions and their returned results.",
            "`facts` reports recent error counts and repeated-call counts.",
            "Match attempts to the same underlying failure rather than the same broad task.",
            "A retry counts only when the state shows a new attempt after that failure.",
            "A failure followed by evidence of resolution is not persistent.",
            "If events do not identify the same failure, treat recurrence as absent.",
        ),
        "Is the same failure still occurring across multiple attempts?",
        "True when multiple visible attempts encounter the same unresolved failure.",
        "False when the failure is different, resolved, or not clearly repeated in the state.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_REPEATED_ACTION_NO_INFORMATION,
        (
            "This check looks for an unchanged tool action repeated without useful new information.",
            "`facts` lists repeated call signatures observed since the last refresh.",
            "`recent` shows the newest calls and the results visible to the agent.",
            "`brief` records the current step and relevant unresolved items.",
            "Compare the action and its arguments across the repeated calls.",
            "Then compare their results for information relevant to the requested work.",
            "A repeated signature alone is insufficient when its result adds useful information.",
            "When the state cannot show both repetition and its results, treat the signal as absent.",
        ),
        "Has the same tool action been repeated without adding relevant information?",
        "True when a repeated action has the same effective inputs and adds no relevant information.",
        "False when the action differs, adds useful information, or the state cannot establish both facts.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_DRIFT_FROM_USER_GOAL,
        (
            "This check compares the current work with the outcome the user requested.",
            "`request` is the source for the user's goal and stated scope.",
            "`brief` records the verified goal, current step, and next steps.",
            "`recent` shows actions the agent has actually taken most recently.",
            "Trace whether those actions advance the requested outcome or a necessary substep.",
            "A changed method can still remain aligned with the same goal.",
            "Unrelated work is different from an ordinary delay or supporting investigation.",
            "If the state does not establish a mismatch, treat drift as absent.",
        ),
        "Are recent actions drifting away from the user's original goal?",
        "True when visible work pursues an outcome with no supported connection to the requested goal.",
        "False when the work remains connected to the goal or the state does not establish a mismatch.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_USER_CONSTRAINT_OMITTED,
        (
            "This check looks for an explicit user constraint missing from current work.",
            "`request` contains the user's stated limits, exclusions, and required conditions.",
            "`brief` summarizes verified progress and planned next steps.",
            "`recent` records the newest actions and their results.",
            "Identify a constraint stated directly in the request.",
            "Check whether the visible plan or completed work addresses that constraint.",
            "Silence about a constraint does not by itself prove that it was omitted.",
            "If the state cannot connect an explicit constraint to a current omission, treat it as absent.",
        ),
        "Does current work omit an explicit constraint from the user's request?",
        "True when the request states a constraint and the visible plan or work leaves it unaddressed.",
        "False when constraints are addressed or the state does not establish a specific omission.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_CLAIM_CONTRADICTS_EVIDENCE,
        (
            "This check compares a recent agent claim with verified tool evidence.",
            "`recent` contains the newest numbered events, including visible tool results.",
            "`brief` keeps only progress and quotations verified against cited events.",
            "Locate a recent claim about what happened or what a tool established.",
            "Compare that claim with the relevant returned result in the shared state.",
            "A difference in wording is not a contradiction when the meaning agrees.",
            "A claim with no corresponding evidence cannot establish a contradiction by itself.",
            "If both sides of the comparison are not visible, treat this signal as absent.",
        ),
        "Does a recent agent claim contradict verified tool evidence?",
        "True when a visible recent claim conflicts with the result of the relevant tool call.",
        "False when the claim agrees with the result or the state lacks both sides of the comparison.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_DISPROVEN_ASSUMPTION_CONTINUES,
        (
            "This check looks for continued action based on an assumption already disproven in the run.",
            "`recent` preserves the newest actions, observations, and corrections in order.",
            "`brief` records verified progress and unresolved failures.",
            "Find an assumption that the visible evidence directly rules out.",
            "Then check whether later activity still relies on that same assumption.",
            "A new test of an uncertain idea does not show continued reliance after disproof.",
            "The assumption and later action must refer to the same premise.",
            "If the state does not show disproof followed by reliance, treat the signal as absent.",
        ),
        "Does the agent keep acting on an assumption the run has disproven?",
        "True when later visible work still relies on a premise already contradicted by run evidence.",
        "False when no disproof and continued reliance are both visible in the state.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_EARLIER_EVIDENCE_IGNORED,
        (
            "This check looks for relevant earlier evidence that later work fails to use.",
            "`brief` preserves verified goal evidence and the current state of named items.",
            "`recent` shows the newest events that may refer back to earlier findings.",
            "Identify evidence that bears directly on the current step or unresolved problem.",
            "Check whether later actions or claims account for that evidence.",
            "Not repeating an old detail is not the same as losing or ignoring it.",
            "The evidence must remain relevant to the work now underway.",
            "If the state does not expose relevant evidence and later omission, treat this signal as absent.",
        ),
        "Is relevant earlier evidence being lost or ignored by the current work?",
        "True when later visible work overlooks earlier verified evidence relevant to its current step.",
        "False when the evidence is accounted for, no longer relevant, or not visible enough to compare.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_FIX_INTRODUCES_FAILURE,
        (
            "This check asks whether an attempted fix is followed by a new failure.",
            "`recent` gives the order of recent fix actions and their returned results.",
            "`brief` records open failures and the approaches that were tried.",
            "Separate the original problem from a failure that appears after a fix attempt.",
            "The later problem must be tied by the visible sequence to that attempted change.",
            "A failure that was already present is not newly introduced by the fix.",
            "A successful change followed by an unrelated error does not establish this signal.",
            "If the state cannot identify a new failure after a fix, treat it as absent.",
        ),
        "Have attempted fixes introduced new failures in the run?",
        "True when a visible fix attempt is followed by a newly reported failure attributable to that change.",
        "False when no new failure follows a fix or the state cannot connect the two.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_PLAN_OSCILLATES,
        (
            "This check looks for a plan that repeatedly changes direction without measurable progress.",
            "`brief` records the current step, next steps, and approaches already taken.",
            "`recent` shows how those plans changed across the newest run events.",
            "`facts` provides iteration and call counts for interpreting the activity.",
            "Look for repeated returns between competing directions rather than one considered revision.",
            "Check whether each change produces a verified result or advances a named item.",
            "A justified plan update after new evidence is not unproductive oscillation.",
            "If repeated reversals or lack of progress are not visible, treat this signal as absent.",
        ),
        "Is the plan oscillating between directions without measurable progress?",
        "True when repeated direction changes are visible without verified progress on the requested work.",
        "False when the plan is stable, changes for evidence-based reasons, or makes visible progress.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_LOST_CONTINUITY,
        (
            "This check looks for observable confusion linked to accumulated run activity.",
            "`facts` reports how many iterations, calls, and tokens the run has used.",
            "`brief` summarizes the verified current step and unresolved work.",
            "`recent` preserves the newest statements and actions in order.",
            "Look for visible loss of continuity, such as repeated uncertainty about established state.",
            "A large count alone does not show confusion or lost context.",
            "A single correction can be ordinary learning rather than a continuity failure.",
            "If accumulated activity and a continuity problem are not both supported, treat the signal as absent.",
        ),
        "Does the growing run show lost continuity or confused state?",
        "True when later events show confusion or loss of established state as the run grows.",
        "False when only run size is visible or the events do not establish a continuity problem.",
    ),
    _question(
        JevComputeQuestionKey.FRESH_AGENT_BRIEF_SUPPORTS_RESUME,
        (
            "This check examines whether the verified brief preserves enough state to resume the task.",
            "`request` supplies the original goal and the user's constraints.",
            "`brief` records verified goal evidence, the current step, and planned next steps.",
            "It can also retain named items, approaches, and unresolved failures.",
            "Use `recent` only to interpret the event references already present in the brief.",
            "A useful handoff makes clear what has been done and what remains.",
            "Do not fill gaps with assumptions that the shared state does not support.",
            "If the brief omits essential goal or progress context, treat resume readiness as absent.",
        ),
        "Does the verified brief contain enough state for a fresh agent to resume?",
        "True when the brief supports the goal, verified progress, current position, and an actionable next step.",
        "False when essential context is missing, unclear, or only inferable from unsupported assumptions.",
    ),
)


FORK_AGENT_QUESTIONS = (
    _question(
        JevComputeQuestionKey.FORK_AGENT_DISTINCT_APPROACHES,
        (
            "This check looks for multiple plausible approaches to one unresolved goal.",
            "`request` identifies the result the user asked for.",
            "`brief` records the verified goal, current progress, and approaches already taken.",
            "`facts` gives exact counts about the run's current state.",
            "`recent` shows the newest run events in order.",
            "Find at least two approaches that address the same unresolved goal.",
            "They must differ in their central action, not merely in wording.",
            "If the state does not support two such approaches, treat them as absent.",
        ),
        "Are there two or more genuinely distinct plausible approaches to the same unresolved goal?",
        "True when the state supports at least two different, plausible approaches to one unresolved requested goal.",
        "False when fewer than two such approaches are supported or they address different goals.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_SAME_VERIFIED_STATE,
        (
            "This check asks whether the alternative paths share one current starting point.",
            "`brief` records verified progress and the current step.",
            "`recent` shows observations that changed or confirmed that state.",
            "`facts` gives exact run counts at the checkpoint.",
            "Compare what each path requires before it can begin.",
            "Both paths must use the same already verified facts and completed work.",
            "A path that depends on the other path's result starts from a different state.",
            "If one shared starting state is not supported, treat the signal as absent.",
        ),
        "Can the alternative paths start from the same verified state?",
        "True when both paths can use the same verified progress, facts, and current position.",
        "False when either path requires a different or not-yet-established starting state.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_INDEPENDENT_PATHS,
        (
            "This check looks for approaches that can progress without depending on one another.",
            "`brief` records the steps and dependencies already known in the run.",
            "`recent` shows which actions require earlier results.",
            "`request` keeps the user's goal in view while comparing the paths.",
            "Trace each approach through its stated next actions.",
            "An independent path does not need the other path's intermediate output.",
            "Shared purpose does not make paths dependent when their work can proceed separately.",
            "If a dependency is unclear, do not infer independence from the option names.",
        ),
        "Can the alternative paths proceed independently of each other's intermediate results?",
        "True when the described next actions on each path do not require the other's output.",
        "False when one path depends on the other's result or the state cannot establish independence.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_BOUNDED_EXPERIMENTS,
        (
            "This check examines whether each approach can be tested as a bounded experiment.",
            "`brief` records current approaches and the work still unresolved.",
            "`recent` shows attempted actions and their outcomes.",
            "A bounded experiment has a stated action and an observable stopping point.",
            "Each path must be testable without expanding into an open-ended task.",
            "The proposed test must leave a result that can be inspected in the run.",
            "An approach label without an action or endpoint is not a bounded experiment.",
            "If either path lacks a testable bound, treat this signal as absent.",
        ),
        "Can each alternative path be tested as a bounded experiment?",
        "True when each path has a bounded action and an observable result or stopping point.",
        "False when either path is open-ended or has no inspectable result.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_COMMON_SUCCESS_CONDITION,
        (
            "This check asks whether both paths can be judged against the same success condition.",
            "`request` states the user's required outcome and constraints.",
            "`brief` records the goal and verified progress toward it.",
            "`recent` may show how current results are being checked.",
            "Name the requested condition that would count as success for each path.",
            "The path-specific steps may differ while the outcome test remains common.",
            "Two outcomes that cannot be compared under one condition do not share this signal.",
            "If the request and brief do not support a common test, treat it as absent.",
        ),
        "Can outcomes from both paths be compared against the same success condition?",
        "True when one request-grounded success condition applies to both paths.",
        "False when their outcomes require unrelated success conditions or no common condition is stated.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_NO_CLEAR_WINNER,
        (
            "This check looks for unresolved evidence between the plausible paths.",
            "`brief` summarizes the approaches and evidence gathered so far.",
            "`recent` records the newest results that may favor one path.",
            "Compare the available evidence using the goal stated in `request`.",
            "A clear winner requires relevant evidence that favors one path over the alternatives.",
            "A difference in how much each path has been tried is not itself proof.",
            "Do not treat missing evidence as evidence that paths are equally good.",
            "If the state does not establish whether a winner is clear, treat this signal as absent.",
        ),
        "Does the current evidence leave the plausible paths without a clear winner?",
        "True when available relevant evidence does not establish one path as the clear choice.",
        "False when the evidence clearly favors one path or is too incomplete to compare them.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_NON_FORECLOSING,
        (
            "This check asks whether trying one path leaves the alternatives available.",
            "`request` and `brief` identify the goal and current state each path addresses.",
            "`recent` shows actions already taken and any visible side effects.",
            "Consider whether one path consumes a resource needed by another.",
            "Also check for order requirements that make later alternatives impossible.",
            "A reversible trial can preserve options even if it produces a different result.",
            "A path that permanently rules out another is foreclosing it.",
            "If the state does not show whether alternatives remain available, treat this signal as absent.",
        ),
        "Does the current state show that trying one path leaves the other plausible paths available?",
        "True when visible actions and constraints allow the alternatives to remain open after a trial.",
        "False when one path forecloses another or the state cannot establish that options remain open.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_ISOLATED_SIDE_EFFECTS,
        (
            "This check looks for side effects that can be kept separate across paths.",
            "`brief` records the current work and named items.",
            "`recent` shows visible writes, tool actions, and their targets.",
            "`request` identifies shared resources or limits that matter to the task.",
            "Compare the targets each path would read or change.",
            "Isolation means one path's effects do not silently alter the other's inputs.",
            "Separate names alone do not prove that underlying state is independent.",
            "If the state cannot identify bounded effects, treat isolation as absent.",
        ),
        "Can writes or other side effects from the paths be isolated from one another?",
        "True when the state supports separate targets or controlled effects for each path.",
        "False when effects overlap in an uncontrolled way or the state cannot establish isolation.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_PARALLEL_EVIDENCE,
        (
            "This check looks for independent trial results that can become visible without serial dependency.",
            "`brief` records the current goal, approaches, and active next steps.",
            "`recent` shows actions and outputs in their observed order.",
            "Compare whether each path can produce its own inspectable result.",
            "The result must not wait on the other path's intermediate output.",
            "A shared final comparison is compatible with independently gathered evidence.",
            "The question concerns available parallel evidence, not whether extra agents should be launched.",
            "If the paths are sequentially dependent, treat this signal as absent.",
        ),
        "Can each path's outcome be inspected before another path supplies an intermediate result?",
        "True when each path can yield an inspectable result without waiting on the other path.",
        "False when results depend on serial handoffs or the state does not show separate outcomes.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_DIFFERENT_HYPOTHESES,
        (
            "This check asks whether the paths test different meaningful explanations or mechanisms.",
            "`brief` records the proposed approaches and the unresolved problem.",
            "`recent` shows what the run has already established.",
            "`request` supplies the outcome the explanations must address.",
            "Identify the distinct claim each path would test against the shared goal.",
            "Different commands that test the same claim do not establish different hypotheses.",
            "The difference must matter to what the run would conclude or do next.",
            "If no distinct request-relevant hypotheses are visible, treat this signal as absent.",
        ),
        "Does each path test a different meaningful hypothesis about the unresolved goal?",
        "True when the paths test distinct, request-relevant explanations or mechanisms.",
        "False when they test the same claim or their difference has no bearing on the goal.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_SELECTABLE_RESULT,
        (
            "This check looks for a result from one path that can be selected or integrated.",
            "`request` gives the outcome that any adopted result must serve.",
            "`brief` records existing work and the place the result would fit.",
            "`recent` shows how current work consumes findings or changes.",
            "A usable result can be compared and then chosen or incorporated into the main work.",
            "The paths may produce competing answers if the shared goal still guides selection.",
            "A result with no route back into requested work is not selectable in this sense.",
            "If the state does not show how a result could be used, treat this signal as absent.",
        ),
        "Can a result from one path be selected or integrated into the main work?",
        "True when the state supports comparing a path result and using it toward the requested outcome.",
        "False when results cannot guide a choice or connect back to the requested work.",
    ),
    _question(
        JevComputeQuestionKey.FORK_AGENT_REQUEST_ALIGNED_PATHS,
        (
            "This check compares the alternative paths with the user's requested goal.",
            "`request` defines the outcome and any explicit scope limits.",
            "`brief` records how each current approach relates to the unresolved goal.",
            "`recent` shows the actions that gave rise to those approaches.",
            "Trace each path to work that advances or verifies the requested outcome.",
            "A different method can remain aligned when it serves the same requested result.",
            "Unrequested side work does not become relevant merely because it is technically interesting.",
            "If the state does not connect an alternative to the request, treat it as unaligned.",
        ),
        "Do the alternative paths address the requested goal rather than unrelated work?",
        "True when each path has a supported connection to the user's requested outcome.",
        "False when a path pursues unrelated work or its connection to the request is unsupported.",
    ),
)


SUBAGENT_QUESTIONS = (
    _question(
        JevComputeQuestionKey.SUBAGENT_BOUNDED_SUBTASK,
        (
            "This check looks for a bounded subtask that can stand on its own.",
            "`request` states the user's requested result.",
            "`brief` records the verified goal, current step, named items, and next steps.",
            "`recent` shows the newest actions and their results.",
            "Identify work grounded in those fields rather than inventing extra scope.",
            "The subtask needs a clear boundary and a result or stopping point.",
            "It must not require the main agent to supply missing decisions as it proceeds.",
            "If scope or completion cannot be identified, treat the subtask as absent.",
        ),
        "Is there a bounded, independently executable subtask in the current work?",
        "True when the state shows a scoped unit of work with a clear result or stopping point.",
        "False when the work is open-ended, dependent on missing decisions, or unsupported by the state.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_EXPLICIT_DELIVERABLE,
        (
            "This check examines whether the separate work has a clear deliverable.",
            "`request` states what result the user needs.",
            "`brief` records current work and any proposed subtask.",
            "`recent` shows artifacts, findings, or outcomes already produced.",
            "Name what a helper would return when its work is complete.",
            "The deliverable must be inspectable by the main agent.",
            "Activity without an identifiable result is not a deliverable.",
            "If the shared state does not specify an output or completion result, treat it as absent.",
        ),
        "Does the independent subtask have an explicit deliverable?",
        "True when the state identifies a concrete output or finding the helper would return.",
        "False when the expected result is unspecified, uninspectable, or not distinct from activity.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_PACKAGED_INPUTS,
        (
            "This check asks whether the subtask's starting information can be packaged from shared state.",
            "`request` supplies the original goal and its explicit constraints.",
            "`brief` records verified progress and the current position.",
            "`recent` preserves relevant actions and results from the run.",
            "Identify the inputs needed to complete the bounded work.",
            "Those inputs must be available in these fields without hidden conversation history.",
            "A missing decision or source cannot be supplied by assuming what the main agent knows.",
            "If essential inputs are not present in the shared state, treat packaging as absent.",
        ),
        "Can the subtask's required inputs be packaged from the request and verified brief?",
        "True when the required starting context is present in `request`, `brief`, or relevant `recent` events.",
        "False when essential context depends on unavailable history, assumptions, or new decisions.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_OWN_TOOL_INTERACTIONS,
        (
            "This check looks for a work unit with its own necessary tool interactions.",
            "`brief` records the current step and discrete work items.",
            "`recent` shows tool actions and their results during the run.",
            "`request` establishes why the proposed work belongs in the task.",
            "Identify the bounded actions needed to finish that work unit.",
            "They should be separable from the main agent's central reasoning steps.",
            "A subtask that only repeats a judgment already visible in the brief has no independent tool work.",
            "If separate tool interactions are not supported by the state, treat this signal as absent.",
        ),
        "Does the subtask require its own bounded tool interactions?",
        "True when the work unit requires distinct tool actions that can be performed within its scope.",
        "False when it needs no separate interactions or its actions are inseparable from the main path.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_NO_MIDTASK_DECISIONS,
        (
            "This check asks whether the subtask can proceed without decisions from the main agent midway.",
            "`request` contains constraints that may limit available choices.",
            "`brief` records the current plan and any unresolved questions.",
            "`recent` shows decisions or clarifications already made.",
            "Follow the proposed work from its starting inputs to its stated deliverable.",
            "The helper must have enough direction to finish that bounded path independently.",
            "A need to choose among new user-facing or task-defining options breaks independence.",
            "If an intervening decision is required or the state is unclear, treat this signal as absent.",
        ),
        "Can the subtask proceed without the main agent making decisions midway?",
        "True when its scope, inputs, and stopping condition let the helper finish without an intervening choice.",
        "False when the path depends on a new decision or the shared state does not settle that question.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_SEPARATE_FROM_CENTRAL_PATH,
        (
            "This check distinguishes separate work from the main agent's central decision path.",
            "`request` defines the result and constraints the main agent must handle.",
            "`brief` records the current step, approaches, and unresolved items.",
            "`recent` shows which results the next central decision depends on.",
            "Compare the proposed subtask with those central choices.",
            "Separate work can inform the main path without making its core choice on the main agent's behalf.",
            "A step that determines the main path's next action is not separate in this sense.",
            "If the state does not show this distinction, treat separation as absent.",
        ),
        "Is the subtask separate from the main agent's central decision path?",
        "True when it produces supporting work without owning a decision reserved for the main path.",
        "False when it performs the central choice itself or the relationship is unclear.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_INTEGRATABLE_RESULT,
        (
            "This check examines whether the subtask's result has a route back into the run.",
            "`request` states the outcome the main agent must deliver.",
            "`brief` records current progress and unresolved work.",
            "`recent` shows how prior findings have been used.",
            "Connect the proposed result to a specific next step or requested item.",
            "The main agent must be able to inspect and use the returned result.",
            "A detached artifact with no relation to remaining work is not integratable.",
            "If the state does not show a usable connection, treat integration as absent.",
        ),
        "Can the subtask's result be handed back and integrated into the main work?",
        "True when the result can be inspected and applied to a current request or unresolved step.",
        "False when there is no supported route to use the result in the main work.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_PARALLEL_PROGRESS,
        (
            "This check looks for a separate work unit that can proceed while the main work continues.",
            "`brief` records current and next steps.",
            "`recent` shows dependencies between the newest actions and results.",
            "`request` identifies the work that must remain on the main path.",
            "Compare the subtask's inputs with the main path's outstanding actions.",
            "The two units must be able to advance without waiting for each other's intermediate result.",
            "A common final integration point does not make their earlier work dependent.",
            "If one unit must pause for the other, treat parallel progress as absent.",
        ),
        "Can this subtask proceed while the main agent continues another active step?",
        "True when the state shows independent work that does not wait on the main path's intermediate result.",
        "False when the subtask and main step are sequentially dependent or the dependency is unclear.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_FOCUSED_CONTEXT,
        (
            "This check looks for a focused body of evidence or material that forms its own work unit.",
            "`request` identifies which sources or results matter to the user.",
            "`brief` records named items and the main agent's current focus.",
            "`recent` shows material already inspected and work still outstanding.",
            "Identify a coherent evidence set that can be examined within the subtask's boundary.",
            "Its relevant inputs should be distinguishable from the main agent's other active material.",
            "A separate topic label alone does not establish a focused body of evidence.",
            "If the state does not identify such a set, treat this signal as absent.",
        ),
        "Does the state identify a distinct evidence set that can be examined in a focused context?",
        "True when the state identifies a bounded evidence set distinct from other active run material.",
        "False when the material is not separable or no focused evidence set is shown.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_PARTITIONABLE_ITEMS,
        (
            "This check asks whether multiple independent requested items can be partitioned.",
            "`request` identifies any explicitly named targets or collection scope.",
            "`brief` records named items and their progress status.",
            "`recent` shows which items have been handled and what remains.",
            "Compare the unfinished items for dependencies on one another.",
            "Partitioning applies when each unit can be handled from its own stated inputs.",
            "A numbered list is not independent when its items rely on shared intermediate decisions.",
            "If multiple independent items are not visible, treat this signal as absent.",
        ),
        "Are multiple independent items present that can be partitioned into separate work units?",
        "True when the state shows at least two unfinished items with separable inputs and outcomes.",
        "False when fewer than two such items are supported or their work is interdependent.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_ISOLATED_WRITES,
        (
            "This check looks for subtask work that avoids conflicting writes or shared mutable state.",
            "`request` may state limits on changes or shared resources.",
            "`brief` records current work and named targets.",
            "`recent` shows visible reads, writes, and tool results.",
            "Identify which shared targets the subtask would change.",
            "Compare those targets with ongoing main-agent actions in the run.",
            "Separate read-only work or disjoint targets can avoid competing mutations.",
            "If writes overlap or their isolation is not shown, treat this signal as absent.",
        ),
        "Can the subtask avoid conflicting writes and shared mutable state?",
        "True when visible scope permits read-only work or changes to isolated targets.",
        "False when mutable targets overlap or the state does not establish safe separation.",
    ),
    _question(
        JevComputeQuestionKey.SUBAGENT_SUBSTANTIVE_WORK,
        (
            "This check asks whether the independent work contains enough substantive activity.",
            "`request` defines the size and importance of the requested outcome.",
            "`brief` records the steps, named items, and unresolved work.",
            "`recent` shows the amount and kind of work already underway.",
            "Estimate the bounded actions needed from the state rather than from an invented plan.",
            "The unit should involve meaningful investigation, transformation, or verification.",
            "A tiny isolated action is not substantive merely because it can be delegated.",
            "If the state does not support meaningful independent work, treat this signal as absent.",
        ),
        "Is there enough substantive work for an independent helper?",
        "True when the bounded unit contains meaningful investigation, transformation, or verification.",
        "False when it is trivial, unsupported, or inseparable from the main agent's work.",
    ),
)

__all__ = ["FORK_AGENT_QUESTIONS", "FRESH_AGENT_QUESTIONS", "SUBAGENT_QUESTIONS"]
