"""Context Protocol Header

Description:
    Exports the root Vidbyte SDK client and top-level public tool, agent, context, and strategy contracts.
Purpose:
    Keeps common SDK imports concise while leaving specialized built-in tools in
    their category packages.
Architecture:
    - VidbyteSDK: Root namespace client.
    - Agent exports: BaseAgent, AgentCard, AgentMessage, AgentRegistry, AgentRunnerConfig, AgentSpec.
    - Tool exports: BaseTool, ToolCall, ToolExecutor, ToolParameter, ToolPermission, ToolRegistry, ToolResult, ToolSpec, ToolStatus, ToolsFormatter.
    - MCP exports: McpServerConfig, McpServerHandle, McpToolPermission.
    - Context exports: BaseAgentContext, BaseContext, ContextBudget, ContextPermissions.
    - Preset exports: BudgetPreset, PermissionPreset.
    - Strategy exports: BaseStrategy, StrategyContext, StrategyResult.
    - Pipeline exports: BasePipeline, ConditionalPipeline, ParallelPipeline, PipelineNode, SequentialPipeline.
    - Error exports: McpError, McpConnectionError, McpInitializeError, McpToolDiscoveryError, McpToolExecutionError, McpAttachmentError, PipelineExecutionError.
Key Functions / Exports:
    - VidbyteSDK: Main SDK entry point.
    - BaseAgent: Base class for building agents.
    - BaseTool: Base class for building tools.
    - BaseContext: Base class for managing conversation contexts.
Relation to codebase as a whole:
    Acts as the primary public API entry point of the entire SDK, unifying all sub-packages (agents, context, tools, mcp, pipelines, strategies, middleware) into a single export surface for consumers.
Similar files:
    - vidbyte/context/__init__.py: Exposes public context management namespace.
    - vidbyte/agents/__init__.py: Exposes agent contracts.
    - vidbyte/tools/__init__.py: Exposes tool abstractions.
"""

from __future__ import annotations

from vidbyte.agents import (
    Agent,
    AgentClient,
    AgentCard,
    AgentInput,
    AgentMessage,
    AgentRegistry,
    AgentRunnerConfig,
    AgentRuntimeConfig,
    AgentRuntimeStats,
    AgentSpec,
    AgentStopReason,
    BaseAgent,
)
from vidbyte.client import VidbyteSDK
from vidbyte.evals import (
    AtomicClaimsJudge,
    BaseGrader,
    BinaryJudge,
    BranchSolveMergeJudge,
    ChainOfAspectsJudge,
    ChainOfThoughtJudge,
    ComparisonReport,
    ConstitutionalJudge,
    ContainsGrader,
    CriteriaDecompositionJudge,
    EvalCase,
    EvalClient,
    EvalRegistry,
    EvalResult,
    EvalRunner,
    EvalSuite,
    EvalSuiteResult,
    ExactMatchGrader,
    FewShotJudge,
    GraderResult,
    JSONSchemaGrader,
    LLMJudgeGrader,
    LLMRubricJudge,
    MetaJudge,
    MixtureOfPromptsJudge,
    MultiAgentDebateJudge,
    MultiAgentRubricJudge,
    PairwiseJudge,
    PanelJudge,
    PeerReviewJudge,
    RegexMatchGrader,
    RubricGrader,
    SelfEvalJudge,
    SelfReferenceJudge,
    StructuredRubricJudge,
)
from vidbyte.context import (
    ArtifactContextItem,
    BaseAgentContext,
    BaseContext,
    ContextBudget,
    ContextItem,
    ContextManager,
    ContextPermissions,
    ContextWindow,
    ContextWindowAlgorithm,
    DocumentContextItem,
    EnvironmentContextItem,
    FileContextItem,
    GitDiffContextItem,
    MemoryContextItem,
    MultiProviderAgenticGraderAlgorithm,
    PlanContextItem,
    ProgressContextItem,
    ReflexionAlgorithm,
    ResponseContextItem,
    TaskContextItem,
    TextContextItem,
    ToolCallContextItem,
    ToolResultAdmission,
)
from vidbyte.tools.builtins.context_primitives import (
    ContextListTool,
    ContextRemoveTool,
    ContextUpsertTool,
)
from vidbyte.lib.enums import BudgetPreset, ModelModality, PermissionPreset, Prompt
from vidbyte.lib.errors import (
    McpAttachmentError,
    McpConnectionError,
    McpError,
    McpInitializeError,
    McpToolDiscoveryError,
    McpToolExecutionError,
    PipelineExecutionError,
    TracerConfigurationError,
)
from vidbyte.lib.tracing import NullTracer, TracerBase
from vidbyte.middleware import (
    AgentMiddleware,
    AuditLogMiddleware,
    CanaryTripwireMiddleware,
    ConfusedDeputyGuardMiddleware,
    HoneypotToolMiddleware,
    MiddlewareAction,
    MiddlewareContext,
    MiddlewareDecision,
    MiddlewareEvent,
    MiddlewareHook,
    MiddlewarePipeline,
    ModelRetryMiddleware,
    RuntimeLimitMiddleware,
    TokenRateLimitMiddleware,
    ToolPolicyMiddleware,
)
from vidbyte.pipelines import (
    BasePipeline,
    ConditionalPipeline,
    MapReducePipeline,
    ParallelPipeline,
    PipelineNode,
    SequentialPipeline,
)
from vidbyte.prompts import Prompts
from vidbyte.strategies import (
    BaseStrategy,
    BaseStrategyUtils,
    ChainOfDraftStrategy,
    ChainOfThoughtStrategy,
    PlanAndExecuteStrategy,
    ReActStrategy,
    ReflexionStrategy,
    SelfConsistencyStrategy,
    SelfRefinementStrategy,
    SkeletonOfThoughtStrategy,
    StepBackStrategy,
    StrategyChain,
    StrategyContext,
    StrategyResult,
    TreeOfThoughtsStrategy,
)
from vidbyte.strategies.multi_agent import MultiAgentConsensusStrategy
from vidbyte.tools import (
    BaseTool,
    FunctionTool,
    ToolCall,
    ToolCallContext,
    ToolCallState,
    ToolExecutor,
    ToolMixin,
    ToolParameter,
    ToolPermission,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    ToolStatus,
    Tools,
    ToolsFormatter,
    tool,
    vidbyte_tool,
)
from vidbyte.mcp_server import McpStudioServer
from vidbyte.tools.mcp import (
    McpServerConfig,
    McpServerHandle,
    McpToolPermission,
)

__all__ = [
    "Agent",
    "NullTracer",
    "TracerBase",
    "TracerConfigurationError",
    "AgentCard",
    "AgentClient",
    "AgentInput",
    "AgentMiddleware",
    "AuditLogMiddleware",
    "CanaryTripwireMiddleware",
    "ConfusedDeputyGuardMiddleware",
    "AgentMessage",
    "AgentRegistry",
    "AgentRunnerConfig",
    "AgentRuntimeConfig",
    "AgentRuntimeStats",
    "AgentSpec",
    "AgentStopReason",
    "ArtifactContextItem",
    "BaseAgent",
    "BaseAgentContext",
    "BaseContext",
    "BasePipeline",
    "BaseStrategy",
    "BaseStrategyUtils",
    "BaseTool",
    "BudgetPreset",
    "ChainOfDraftStrategy",
    "ChainOfThoughtStrategy",
    "ContextBudget",
    "ContextItem",
    "ContextListTool",
    "ContextManager",
    "ContextPermissions",
    "ContextRemoveTool",
    "ContextUpsertTool",
    "ContextWindow",
    "ContextWindowAlgorithm",
    "DocumentContextItem",
    "EnvironmentContextItem",
    "FileContextItem",
    "GitDiffContextItem",
    "MemoryContextItem",
    "PlanContextItem",
    "McpAttachmentError",
    "McpConnectionError",
    "McpError",
    "McpInitializeError",
    "McpServerConfig",
    "McpServerHandle",
    "McpStudioServer",
    "McpToolDiscoveryError",
    "McpToolExecutionError",
    "McpToolPermission",
    "MiddlewareAction",
    "MiddlewareContext",
    "MiddlewareDecision",
    "MiddlewareEvent",
    "MiddlewareHook",
    "MiddlewarePipeline",
    "ModelRetryMiddleware",
    "HoneypotToolMiddleware",
    "MultiAgentConsensusStrategy",
    "MultiProviderAgenticGraderAlgorithm",
    "ConditionalPipeline",
    "MapReducePipeline",
    "ModelModality",
    "ParallelPipeline",
    "PermissionPreset",
    "PipelineExecutionError",
    "PipelineNode",
    "PlanAndExecuteStrategy",
    "ProgressContextItem",
    "Prompt",
    "Prompts",
    "ReActStrategy",
    "ReflexionAlgorithm",
    "ReflexionStrategy",
    "ResponseContextItem",
    "RuntimeLimitMiddleware",
    "SelfConsistencyStrategy",
    "SelfRefinementStrategy",
    "SkeletonOfThoughtStrategy",
    "StepBackStrategy",
    "StrategyChain",
    "StrategyContext",
    "SequentialPipeline",
    "StrategyResult",
    "TaskContextItem",
    "TextContextItem",
    "ToolCall",
    "ToolCallContext",
    "ToolCallContextItem",
    "ToolCallState",
    "ToolResultAdmission",
    "ToolExecutor",
    "ToolParameter",
    "ToolPermission",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "ToolStatus",
    "TokenRateLimitMiddleware",
    "ToolPolicyMiddleware",
    "Tools",
    "ToolsFormatter",
    "TreeOfThoughtsStrategy",
    "VidbyteSDK",
    "AtomicClaimsJudge",
    "BaseGrader",
    "BinaryJudge",
    "BranchSolveMergeJudge",
    "ChainOfAspectsJudge",
    "ChainOfThoughtJudge",
    "ComparisonReport",
    "ConstitutionalJudge",
    "ContainsGrader",
    "CriteriaDecompositionJudge",
    "EvalCase",
    "EvalClient",
    "EvalRegistry",
    "EvalResult",
    "EvalRunner",
    "EvalSuite",
    "EvalSuiteResult",
    "ExactMatchGrader",
    "FewShotJudge",
    "GraderResult",
    "JSONSchemaGrader",
    "LLMJudgeGrader",
    "LLMRubricJudge",
    "MetaJudge",
    "MixtureOfPromptsJudge",
    "MultiAgentDebateJudge",
    "MultiAgentRubricJudge",
    "PairwiseJudge",
    "PanelJudge",
    "PeerReviewJudge",
    "RegexMatchGrader",
    "RubricGrader",
    "SelfEvalJudge",
    "SelfReferenceJudge",
    "StructuredRubricJudge",
    "tool",
    "vidbyte_tool",
]
