"""Context Protocol Header

Description:
    Exports the root Vidbyte SDK client and top-level public tool, agent, context,
    paradigm, and pipeline contracts.
Purpose:
    Keeps common SDK imports concise while leaving specialized built-in tools in
    their category packages.
Architecture:
    - VidbyteSDK: Root namespace client.
    - Agent exports: BaseAgent, AgentCard, AgentMessage, AgentRegistry, AgentRunnerConfig, AgentSpec.
    - Tool exports: BaseTool, ToolCall, ToolExecutor, ToolParameter, ToolPermission, ToolRegistry, ToolResult, ToolSpec, ToolStatus, ToolsFormatter.
    - MCP exports: McpServerConfig, McpServerHandle, McpToolPermission.
    - Context exports: BaseAgentContext, BaseContext, ContextBudget, ContextPermissions.
    - Preset exports: BudgetPreset, PermissionPreset.
    - Pipeline exports: BasePipeline, ConditionalPipeline, ParallelPipeline, PipelineNode, SequentialPipeline.
    - Error exports: McpError, McpConnectionError, McpInitializeError, McpToolDiscoveryError, McpToolExecutionError, McpAttachmentError, PipelineExecutionError.
Key Functions / Exports:
    - VidbyteSDK: Main SDK entry point.
    - BaseAgent: Base class for building agents.
    - BaseTool: Base class for building tools.
    - BaseContext: Base class for managing conversation contexts.
Relation to codebase as a whole:
    Acts as the primary public API entry point of the entire SDK, unifying all sub-packages (agents, context, tools, mcp, pipelines, middleware) into a single export surface for consumers.
Similar files:
    - vidbyte/context/__init__.py: Exposes public context management namespace.
    - vidbyte/agents/__init__.py: Exposes agent contracts.
    - vidbyte/tools/__init__.py: Exposes tool abstractions.
"""

from __future__ import annotations

__version__ = "0.1.0"

from vidbyte.agents import (
    Agent,
    AggregateAgent,
    AggregateConfig,
    AggregateResult,
    AgentClient,
    AgentCard,
    AgentForkSettings,
    AgentInput,
    AgentMessage,
    AgentRegistry,
    AgentRunnerConfig,
    AgentRuntimeConfig,
    AgentRuntimeStats,
    AgentSpec,
    AgentStopReason,
    BaseAgent,
    HandoffAgent,
    MultiProviderAggregator,
    ProposerSpec,
    ToolSettings,
)
from vidbyte.client import VidbyteSDK
from vidbyte.paradigms import (
    AgentRoleSettings,
    ContextFile,
    ContextMinimalFanoutClient,
    ContextMinimalFanoutParadigm,
    ContextMinimalFanoutResult,
    ContextMinimalFanoutSettings,
    EnvironmentContext,
    EnvironmentSummary,
    ImplementationOutput,
    ParadigmClient,
    ParadigmHarness,
    PromptSplitPlan,
    SplitPrompt,
)
from vidbyte.tools.builtins.output_schema import (
    AppendOutputTool,
    DeclareOutputSchemaTool,
    ExtendOutputSchemaTool,
    OutputSchemaBuilder,
    OutputSchemaField,
)
from vidbyte.tools.toolsets import ParadigmMinimalToolset
from vidbyte.evals import (
    AllOfGrader,
    AnyOfGrader,
    BaseGrader,
    Behavior,
    ChoiceMatchGrader,
    ClassificationTemplate,
    ComparisonReport,
    ConciseGroundedAnswerTemplate,
    ContainsAllGrader,
    ContainsGrader,
    EvalCase,
    EvalClient,
    EvalRegistry,
    EvalResult,
    EvalRunner,
    EvalSuite,
    EvalSuiteResult,
    EvalTemplate,
    EvalTemplateRegistry,
    ExactMatchGrader,
    ForbiddenContentGrader,
    GraderResult,
    JSONExactMatchGrader,
    JSONSchemaGrader,
    JSONSubsetGrader,
    LengthGrader,
    LLMJudgeGrader,
    MultipleChoiceTemplate,
    NumericAnswerTemplate,
    NumericMatchGrader,
    PredicateGrader,
    RegexMatchGrader,
    RunProbe,
    RubricGrader,
    SafeCustomerSupportTemplate,
    ShortAnswerFactTemplate,
    StructuredJsonTemplate,
    WeightedGrader,
    templates,
)
from vidbyte.context import (
    ArtifactContextItem,
    BaseAgentContext,
    BaseContext,
    ContextBudget,
    ContextItem,
    ContextManager,
    ContextPermissions,
    ContextWindow,
    ContextWindowAlgorithm,
    ContextWindowPlacement,
    ContextWindowRunContext,
    DocumentContextItem,
    EngineeringHandoff,
    EnvironmentContextItem,
    ErrorCorrectionAlgorithm,
    ErrorCorrectionContextItem,
    FileContextItem,
    GitDiffContextItem,
    Handoff,
    MemoryContextItem,
    MinimalHandoff,
    ResearchHandoff,
    CompactionMode,
    CompactionStats,
    ContextCompactionEngine,
    MultiProviderAgenticGraderAlgorithm,
    InnerContextWindowAlgorithm,
    PlanContextItem,
    ProblemSpaceSearchAlgorithm,
    ProblemSpaceSearchContextItem,
    ProgressContextItem,
    ReflexionAlgorithm,
    ResponseContextItem,
    TaskContextItem,
    TextContextItem,
    ToolCallContextItem,
    ToolResultAdmission,
    TrajectoryCheckpointAlgorithm,
    TrajectoryCheckpointContextItem,
)
from vidbyte.tools.builtins.context_primitives import (
    CREATE_TOOL_REGISTRY,
    CreateContextPrimitiveTool,
    ContextEditTool,
    ContextListTool,
    ContextMoveTool,
    ContextReciteTool,
    ContextRemoveTool,
    ContextStatsTool,
    ContextUpsertTool,
    ContextWindowFactory,
    PrimitiveToolDefinition,
    context_window_tools,
)
from vidbyte.tools.builtins.handoff import CreateHandoffTool
from vidbyte.tools.builtins.run_prompts_sequentially import RunPromptsSequentiallyTool
from vidbyte.tools.builtins.sessions import (
    BatchForkTool,
    CheckpointTool,
    ForkTool,
    ResumeAppendTool,
    ResumeOutputTool,
    ResumeReplaceTool,
    RewindTool,
    SessionTool,
)
from vidbyte.lib.enums import BudgetPreset, PermissionPreset, Prompt
from vidbyte.lib.errors import (
    McpAttachmentError,
    McpConnectionError,
    McpError,
    McpInitializeError,
    McpToolDiscoveryError,
    McpToolExecutionError,
    PipelineExecutionError,
    TracerConfigurationError,
)
from vidbyte.lib.tracing import NullTracer, TracerBase
from vidbyte.trace import (
    ActionTrace,
    ContinualTraceAgent,
    ContinualTraceMiddleware,
    ContinualTracer,
    DebugTracer,
    ParentPolicy,
    SemanticSpanContext,
    SessionTraceController,
    SessionTracer,
    SpanKind,
    SpanSpec,
    Trace,
    TraceComponentSettings,
    TraceController,
    TraceDetail,
    TraceOption,
    TraceProfile,
    TraceSchema,
)
from vidbyte.middleware import (
    AgentMiddleware,
    AuditLogMiddleware,
    CanaryTripwireMiddleware,
    ConfusedDeputyGuardMiddleware,
    HoneypotToolMiddleware,
    MiddlewareAction,
    MiddlewareContext,
    MiddlewareDecision,
    MiddlewareEvent,
    MiddlewareHook,
    MiddlewarePipeline,
    MiddlewareTransform,
    MessageHistoryCompactionMiddleware,
    ModelRetryMiddleware,
    RuntimeLimitMiddleware,
    SummaryCompactionMiddleware,
    TokenRateLimitMiddleware,
    ToolResultCompactionMiddleware,
    ToolPolicyMiddleware,
)
from vidbyte.pipelines import (
    BasePipeline,
    ConditionalPipeline,
    MapReducePipeline,
    ParallelPipeline,
    PipelineNode,
    SequentialPipeline,
)
from vidbyte.prompts import Prompts
from vidbyte.sessions import (
    Checkpoint,
    CheckpointPolicy,
    FileSessionStore,
    ForkOutcome,
    InMemorySessionStore,
    RunState,
    Session,
    SessionClient,
    SessionError,
    SessionMeta,
    SessionNotFoundError,
    SessionScope,
    SessionSerializationError,
    SessionStatus,
    SessionStore,
    SessionStoreError,
    SessionVersionError,
    TraceCapture,
)
from vidbyte.tools import (
    BaseTool,
    FunctionTool,
    ToolCall,
    ToolCallContext,
    ToolCallState,
    ToolExecutor,
    ToolMixin,
    ToolParameter,
    ToolPermission,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    ToolStatus,
    Tools,
    ToolsFormatter,
    tool,
    vidbyte_tool,
)
from vidbyte.providers.output_schema import OutputSchemaFormatter
from vidbyte.mcp_server import McpStudioServer
from vidbyte.tools.mcp import (
    McpServerConfig,
    McpServerHandle,
    McpToolPermission,
)

__all__ = [
    "Agent",
    "ActionTrace",
    "ContinualTraceAgent",
    "ContinualTraceMiddleware",
    "ContinualTracer",
    "TraceOption",
    "TraceSchema",
    "DebugTracer",
    "SessionTracer",
    "NullTracer",
    "OutputSchemaFormatter",
    "AppendOutputTool",
    "AgentRoleSettings",
    "ContextFile",
    "ContextMinimalFanoutClient",
    "ContextMinimalFanoutParadigm",
    "ContextMinimalFanoutResult",
    "ContextMinimalFanoutSettings",
    "DeclareOutputSchemaTool",
    "ExtendOutputSchemaTool",
    "EnvironmentContext",
    "EnvironmentSummary",
    "ImplementationOutput",
    "OutputSchemaBuilder",
    "OutputSchemaField",
    "ParadigmClient",
    "ParadigmHarness",
    "ParadigmMinimalToolset",
    "ParentPolicy",
    "PromptSplitPlan",
    "SemanticSpanContext",
    "SessionTraceController",
    "SpanKind",
    "SpanSpec",
    "SplitPrompt",
    "Trace",
    "TraceComponentSettings",
    "TraceController",
    "TraceDetail",
    "TracerBase",
    "TracerConfigurationError",
    "TraceProfile",
    "AggregateAgent",
    "AggregateConfig",
    "AggregateResult",
    "AgentCard",
    "AgentClient",
    "AgentForkSettings",
    "AgentInput",
    "AgentMiddleware",
    "MultiProviderAggregator",
    "ProposerSpec",
    "AuditLogMiddleware",
    "CanaryTripwireMiddleware",
    "ConfusedDeputyGuardMiddleware",
    "AgentMessage",
    "AgentRegistry",
    "AgentRunnerConfig",
    "AgentRuntimeConfig",
    "AgentRuntimeStats",
    "AgentSpec",
    "AgentStopReason",
    "ToolSettings",
    "ArtifactContextItem",
    "BaseAgent",
    "BaseAgentContext",
    "BaseContext",
    "BasePipeline",
    "BaseTool",
    "BatchForkTool",
    "BudgetPreset",
    "ContextBudget",
    "CREATE_TOOL_REGISTRY",
    "CompactionMode",
    "CompactionStats",
    "ContextCompactionEngine",
    "CreateContextPrimitiveTool",
    "ContextEditTool",
    "ContextItem",
    "ContextListTool",
    "ContextManager",
    "ContextMoveTool",
    "ContextPermissions",
    "ContextReciteTool",
    "ContextRemoveTool",
    "ContextStatsTool",
    "ContextUpsertTool",
    "ContextWindowFactory",
    "CreateHandoffTool",
    "CheckpointTool",
    "RunPromptsSequentiallyTool",
    "ContextWindow",
    "ContextWindowAlgorithm",
    "ContextWindowPlacement",
    "ContextWindowRunContext",
    "DocumentContextItem",
    "EnvironmentContextItem",
    "EngineeringHandoff",
    "FileContextItem",
    "GitDiffContextItem",
    "Handoff",
    "HandoffAgent",
    "MemoryContextItem",
    "MinimalHandoff",
    "PlanContextItem",
    "ResearchHandoff",
    "McpAttachmentError",
    "McpConnectionError",
    "McpError",
    "McpInitializeError",
    "McpServerConfig",
    "McpServerHandle",
    "McpStudioServer",
    "McpToolDiscoveryError",
    "McpToolExecutionError",
    "McpToolPermission",
    "MiddlewareAction",
    "MiddlewareContext",
    "MiddlewareDecision",
    "MiddlewareEvent",
    "MiddlewareHook",
    "MiddlewarePipeline",
    "MiddlewareTransform",
    "MessageHistoryCompactionMiddleware",
    "ModelRetryMiddleware",
    "HoneypotToolMiddleware",
    "InnerContextWindowAlgorithm",
    "MultiProviderAgenticGraderAlgorithm",
    "ConditionalPipeline",
    "ErrorCorrectionAlgorithm",
    "ErrorCorrectionContextItem",
    "MapReducePipeline",
    "ParallelPipeline",
    "PermissionPreset",
    "PipelineExecutionError",
    "PipelineNode",
    "PrimitiveToolDefinition",
    "ProblemSpaceSearchAlgorithm",
    "ProblemSpaceSearchContextItem",
    "ProgressContextItem",
    "Prompt",
    "Prompts",
    "ReflexionAlgorithm",
    "ResponseContextItem",
    "RuntimeLimitMiddleware",
    "SummaryCompactionMiddleware",
    "SequentialPipeline",
    "Checkpoint",
    "CheckpointPolicy",
    "FileSessionStore",
    "ForkOutcome",
    "InMemorySessionStore",
    "RunState",
    "Session",
    "SessionClient",
    "SessionError",
    "SessionMeta",
    "SessionNotFoundError",
    "SessionScope",
    "SessionSerializationError",
    "SessionStatus",
    "SessionStore",
    "SessionStoreError",
    "SessionVersionError",
    "ForkTool",
    "ResumeAppendTool",
    "ResumeOutputTool",
    "ResumeReplaceTool",
    "RewindTool",
    "SessionTool",
    "TraceCapture",
    "TaskContextItem",
    "TextContextItem",
    "ToolCall",
    "ToolCallContext",
    "ToolCallContextItem",
    "ToolCallState",
    "ToolResultAdmission",
    "TrajectoryCheckpointAlgorithm",
    "TrajectoryCheckpointContextItem",
    "ToolExecutor",
    "ToolParameter",
    "ToolPermission",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "ToolStatus",
    "TokenRateLimitMiddleware",
    "ToolResultCompactionMiddleware",
    "ToolPolicyMiddleware",
    "Tools",
    "ToolsFormatter",
    "VidbyteSDK",
    "context_window_tools",
    "BaseGrader",
    "Behavior",
    "AllOfGrader",
    "AnyOfGrader",
    "ChoiceMatchGrader",
    "ClassificationTemplate",
    "ComparisonReport",
    "ConciseGroundedAnswerTemplate",
    "ContainsAllGrader",
    "ContainsGrader",
    "EvalCase",
    "EvalClient",
    "EvalRegistry",
    "EvalResult",
    "EvalRunner",
    "EvalSuite",
    "EvalSuiteResult",
    "EvalTemplate",
    "EvalTemplateRegistry",
    "ExactMatchGrader",
    "ForbiddenContentGrader",
    "GraderResult",
    "JSONExactMatchGrader",
    "JSONSchemaGrader",
    "JSONSubsetGrader",
    "LengthGrader",
    "LLMJudgeGrader",
    "MultipleChoiceTemplate",
    "NumericAnswerTemplate",
    "NumericMatchGrader",
    "PredicateGrader",
    "RegexMatchGrader",
    "RunProbe",
    "RubricGrader",
    "SafeCustomerSupportTemplate",
    "ShortAnswerFactTemplate",
    "StructuredJsonTemplate",
    "WeightedGrader",
    "templates",
    "tool",
    "vidbyte_tool",
]
